import type { SeedCompany, SeedJob } from "./seed-data";

export const INTL_COMPANIES: SeedCompany[] = [
  {
    slug: "aether-ops",
    name: "Aether Ops",
    tagline: "Agents with traces. No magic threads.",
    about:
      "Remote-Europe shop for industrial agent systems. Guardrails, golden sets, token budget on the wall. They hire eval engineers, not prompt magicians.",
    industry: "IA",
    sizeBand: "25–60",
    hqCity: "Berlin",
    hqCountry: "Germany",
    website: "https://aether.example",
    foundedYear: 2023,
    cultureScore: 90,
    hiringVelocity: "fast",
    values: ["Evals before demos", "Public token budget", "Async ±2h"],
  },
  {
    slug: "nimbus-eu",
    name: "Nimbus EU",
    tagline: "Boring runtime. Paid on-call.",
    about:
      "Cloud platform for European scale-ups. FinOps in sprint 1. Remote Europe, timezone ±2h. They refuse lift-and-shift without a cost plan.",
    industry: "Cloud",
    sizeBand: "40–80",
    hqCity: "Amsterdam",
    hqCountry: "Netherlands",
    website: "https://nimbus.example",
    foundedYear: 2020,
    cultureScore: 89,
    hiringVelocity: "steady",
    values: ["FinOps day one", "On-call rare and paid", "Runbooks public"],
  },
  {
    slug: "willem-soc",
    name: "Willem SOC",
    tagline: "Hunting, not ticket theatre.",
    about:
      "Managed SOC for Dutch and German operators. Blue team first. Secret clearance named when required. They pay for a hunt, not a shift of unread alerts.",
    industry: "Cybersécurité",
    sizeBand: "80–200",
    hqCity: "Utrecht",
    hqCountry: "Netherlands",
    website: "https://willem.example",
    foundedYear: 2016,
    cultureScore: 87,
    hiringVelocity: "steady",
    values: ["Blameless post-mortem", "Written on-call", "No Sunday heroes"],
  },
  {
    slug: "lumen-nordic",
    name: "Lumen Nordic",
    tagline: "Every feature has a kWh.",
    about:
      "Energy twins for Nordic cities. CSRD is backlog, not a slide. They hire people who have already lost a public tender.",
    industry: "Climat",
    sizeBand: "80–180",
    hqCity: "Stockholm",
    hqCountry: "Sweden",
    website: "https://lumen-nordic.example",
    foundedYear: 2018,
    cultureScore: 86,
    hiringVelocity: "steady",
    values: ["kWh per feature", "Lost tenders welcome", "Salary published"],
  },
  {
    slug: "emc-munich",
    name: "EMC Munich",
    tagline: "Schematic first. CEM written.",
    about:
      "Electronics bureau in Munich. Analog, FPGA, small series. First day is a board to fix, not an onboarding week.",
    industry: "Électronique",
    sizeBand: "40–90",
    hqCity: "Munich",
    hqCountry: "Germany",
    website: "https://emc-munich.example",
    foundedYear: 2009,
    cultureScore: 88,
    hiringVelocity: "steady",
    values: ["Proto before slides", "IPC held", "German + English review"],
  },
  {
    slug: "fhir-berlin",
    name: "Charité Grid",
    tagline: "A clinician in the room.",
    about:
      "Interop for German university hospitals. FHIR, not a US SaaS resticker. They kill features when a doctor says no.",
    industry: "Santé",
    sizeBand: "100–250",
    hqCity: "Berlin",
    hqCountry: "Germany",
    website: "https://charite-grid.example",
    foundedYear: 2014,
    cultureScore: 85,
    hiringVelocity: "slow",
    values: ["Clinician veto", "HDS / C5 named", "No theatre"],
  },
];

export const INTL_JOBS: SeedJob[] = [
  {
    companySlug: "aether-ops",
    slug: "engineer-agents-aether",
    title: "Agent systems engineer",
    team: "Runtime",
    city: "Remote Europe",
    country: "Germany",
    remoteType: "remote",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 68000,
    salaryMax: 92000,
    equity: true,
    description:
      "Agents that call tools, with traces and guardrails. Not a demo. Remote Europe ±2h. Proof trial before the CV. Salary published. EU AI Act documentation is part of the job, not a side quest.",
    responsibilities: [
      "Ship tool-calling agents with OpenTelemetry traces",
      "Hold a golden set and a rollback",
      "Write the guardrail, not a thread",
    ],
    requirements: ["Python", "Tool orchestration", "Guardrails", "Tracing"],
    nice: ["Industrial OT context", "German or French"],
    benefits: ["Remote ±2h", "Token budget public", "28 days + public holidays of residence"],
    skills: ["Tools", "Guardrails", "Tracing", "Python"],
    daysAgo: 4,
    applicants: 21,
    views: 390,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "aether-ops",
    slug: "eval-engineer-aether",
    title: "Eval engineer LLM",
    team: "Quality",
    city: "Remote Europe",
    country: "Germany",
    remoteType: "remote",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 52000,
    salaryMax: 74000,
    equity: true,
    description:
      "Golden set, drift, token budget. Prompting is not an art here — it is a test battery. Trial is a 6-minute eval design, not a take-home novel.",
    responsibilities: ["Own golden sets", "Catch drift before demo day", "Publish cost per task"],
    requirements: ["Evals", "RAG", "Golden set"],
    nice: ["Pytest", "LangSmith"],
    benefits: ["Remote", "No on-call", "Conference budget"],
    skills: ["Evals", "Golden set", "RAG"],
    daysAgo: 6,
    applicants: 16,
    views: 255,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "nimbus-eu",
    slug: "sre-nimbus-amsterdam",
    title: "SRE / AWS platform",
    team: "Platform",
    city: "Amsterdam",
    country: "Netherlands",
    remoteType: "remote",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 58000,
    salaryMax: 82000,
    equity: false,
    description:
      "Make the runtime boring. FinOps from ticket one. On-call 1/8, paid. Trial: a cost graph, not a leetcode. Dutch 30% ruling discussed in writing if you relocate.",
    responsibilities: ["Keep p99 dull", "Cost per tenant visible", "On-call runbook public"],
    requirements: ["AWS", "Terraform", "Kubernetes", "FinOps"],
    nice: ["Dutch", "Incident command"],
    benefits: ["Remote Europe", "On-call paid", "30% ruling support"],
    skills: ["AWS", "Terraform", "Kubernetes", "FinOps"],
    daysAgo: 3,
    applicants: 19,
    views: 501,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "nimbus-eu",
    slug: "finops-nimbus-eu",
    title: "FinOps engineer",
    team: "Cost",
    city: "Remote Europe",
    country: "Netherlands",
    remoteType: "remote",
    contract: "freelance",
    seniority: "senior",
    salaryMin: 65000,
    salaryMax: 90000,
    equity: false,
    description:
      "Day rate published 650–750 €. Six-month mission. Trial is a waste-line hunt on a fake bill. No « depending on profile ».",
    responsibilities: ["Find waste", "Write the kill ticket", "Teach the team the unit cost"],
    requirements: ["FinOps", "AWS", "Terraform"],
    nice: ["FOCUS spec"],
    benefits: ["TJM published", "Remote", "No Friday meetings"],
    skills: ["FinOps", "AWS", "Terraform"],
    daysAgo: 8,
    applicants: 9,
    views: 160,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "willem-soc",
    slug: "threat-hunter-willem",
    title: "Threat hunter SOC",
    team: "Hunt",
    city: "Utrecht",
    country: "Netherlands",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 54000,
    salaryMax: 76000,
    equity: false,
    description:
      "A hunt shift, not a ticket pile. Trial: tell a false positive and why. Hybrid Utrecht 1 day. On-call 1/6 written, 180 €. Clearance named if needed — never « we'll see ».",
    responsibilities: ["Hunt, not queue", "Write the detection", "Handover that a junior can run"],
    requirements: ["SIEM", "Threat hunting", "MITRE ATT&CK"],
    nice: ["Python", "Dutch"],
    benefits: ["Hybrid 1 day", "On-call paid", "Clearance path written"],
    skills: ["SIEM", "Threat hunting", "MITRE ATT&CK", "Python"],
    daysAgo: 5,
    applicants: 14,
    views: 280,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "lumen-nordic",
    slug: "twin-engineer-stockholm",
    title: "Energy twin engineer",
    team: "Cities",
    city: "Stockholm",
    country: "Sweden",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 48000,
    salaryMax: 68000,
    equity: false,
    description:
      "Every feature has a kWh. Public tenders, not integrator listings. Trial: read a lost RFP and say what you would cut. Salary band published — Swedish transparency, not a French exception.",
    responsibilities: ["Attach kWh to tickets", "Survive a lost tender", "CSRD evidence, not slides"],
    requirements: ["IoT", "Timescale", "Carbon accounting"],
    nice: ["Swedish", "Public procurement"],
    benefits: ["Hybrid Stockholm", "Parental leave as law", "Salary published"],
    skills: ["IoT", "Timescale", "Bilan carbone"],
    daysAgo: 9,
    applicants: 8,
    views: 173,
    ghostRisk: "low",
    collection: "climat",
  },
  {
    companySlug: "emc-munich",
    slug: "analog-munich",
    title: "Analog electronics engineer",
    team: "Hardware",
    city: "Munich",
    country: "Germany",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 52000,
    salaryMax: 68000,
    equity: false,
    description:
      "Schematic, CEM, proto. First day: a board to correct. Trial is an EMC diagnosis, not a personality test. On-site Munich — the scope is in the lab.",
    responsibilities: ["Fix the board", "Write CEM", "Small series, not a slide"],
    requirements: ["Altium", "EMC", "Oscilloscope"],
    nice: ["German", "IPC"],
    benefits: ["Lab on site", "Tarifvertrag discussed", "No onboarding week"],
    skills: ["Altium", "EMC", "Oscilloscope"],
    daysAgo: 11,
    applicants: 5,
    views: 96,
    ghostRisk: "low",
    collection: "terrain",
  },
  {
    companySlug: "fhir-berlin",
    slug: "fhir-interop-berlin",
    title: "FHIR interop engineer",
    team: "Clinical",
    city: "Berlin",
    country: "Germany",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 50000,
    salaryMax: 70000,
    equity: false,
    description:
      "A clinician in the room. FHIR, C5, no resticker. Trial: map a patient encounter, not a culture fit quiz. Hybrid Berlin 2 days.",
    responsibilities: ["Hold FHIR contracts", "Sit with a clinician", "Kill a feature when care says no"],
    requirements: ["FHIR", "HL7", "Interop"],
    nice: ["German B2", "Java"],
    benefits: ["Hybrid 2 days", "Clinician pairing", "Salary published"],
    skills: ["FHIR", "HL7", "HDS"],
    daysAgo: 7,
    applicants: 8,
    views: 142,
    ghostRisk: "low",
    collection: "sante",
  },
  {
    companySlug: "aether-ops",
    slug: "ai-gov-aether-dublin",
    title: "AI governance lead",
    team: "Risk",
    city: "Dublin",
    country: "Ireland",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "lead",
    salaryMin: 72000,
    salaryMax: 98000,
    equity: true,
    description:
      "High-risk systems, ISO 42001, EU AI Act. Europe is hiring; RSE slides are not. Trial: classify a system, write the residual risk. Salary published — Irish pay transparency, not a whisper.",
    responsibilities: ["Classify systems", "Hold ISO 42001 evidence", "Say no to a demo that skips residual risk"],
    requirements: ["AI Act", "ISO 42001", "Model risk"],
    nice: ["Legal adjacent", "French or German"],
    benefits: ["Hybrid Dublin", "Equity", "Conference + notified body travel"],
    skills: ["AI Act", "ISO 42001", "Risque modèle"],
    daysAgo: 2,
    applicants: 6,
    views: 148,
    ghostRisk: "low",
    collection: "remote",
  },
];
