export type MarketCard = {
  code: string;
  name: string;
  nameEn: string;
  desk: string;
  law: string;
  lawEn: string;
  testCulture: "open" | "mixed" | "guarded";
  testNote: string;
  testNoteEn: string;
  gtm: string;
  gtmEn: string;
  partners: string[];
  cities: string[];
};

export const MARKETS: MarketCard[] = [
  {
    code: "FR",
    name: "France",
    nameEn: "France",
    desk: "Siège. Pénurie industrielle + tech. Ton éditorial tenu.",
    law: "Index égalité, grilles, et bientôt transparence salariale UE.",
    lawEn: "Equality index, grids, and incoming EU pay-transparency rules.",
    testCulture: "open",
    testNote: "L’épreuve métier (consignation, circuit) est déjà un argument. Le diplôme reste un réflexe RH — Vera le contourne.",
    testNoteEn: "A craft trial (lockout, circuit) already sells. Degrees remain an HR reflex — Vera goes around them.",
    gtm: "Entreprises ETI, OPCO, bassins Arras / Fos / Lyon. Anti-Indeed, pas anti-France.",
    gtmEn: "Mid-size industrials, training funds, Arras / Fos / Lyon basins. Anti-Indeed, not anti-France.",
    partners: ["AFNOR compétences", "OPCO 2i", "Branches BTP / métallurgie"],
    cities: ["Paris", "Lyon", "Lille", "Marseille", "Arras"],
  },
  {
    code: "DE",
    name: "Allemagne",
    nameEn: "Germany",
    desk: "EMC, FHIR, SOC. Tarifvertrag nommé. L’épreuve doit être « fachlich », pas un game.",
    law: "Entgelttransparenzgesetz + directive UE. Bandes salariales attendues.",
    lawEn: "Pay Transparency Act + EU directive. Salary bands expected.",
    testCulture: "mixed",
    testNote: "Un test court avant candidature passe s’il est métier (CEM, FHIR). Un QCM RH « culture fit » passe pour de l’arrogance.",
    testNoteEn: "A short craft trial (EMC, FHIR) is fine. An HR culture-fit quiz reads as arrogance.",
    gtm: "Bureaux d’études Munich / Berlin, cliniques univ., Mittelstand. Partenaires IHK / TÜV pour créditer l’épreuve.",
    gtmEn: "Munich / Berlin bureaus, university hospitals, Mittelstand. IHK / TÜV partners to credit the trial.",
    partners: ["IHK", "TÜV", "ISO 42001 notified bodies"],
    cities: ["Berlin", "Munich", "Hamburg"],
  },
  {
    code: "NL",
    name: "Pays-Bas",
    nameEn: "Netherlands",
    desk: "Remote + SOC + FinOps. 30% ruling écrit. Anglais de travail.",
    law: "Salaire dans l’annonce de plus en plus attendu. Directives UE.",
    lawEn: "Salary in the ad is increasingly expected. EU rules apply.",
    testCulture: "open",
    testNote: "Le marché tech NL aime les trials. Tenir 6 minutes > un take-home de 6 heures.",
    testNoteEn: "Dutch tech likes trials. Six minutes held beats a six-hour take-home.",
    gtm: "Amsterdam / Utrecht, scale-ups cloud, SOC managés. Angle anti-spam CV IA.",
    gtmEn: "Amsterdam / Utrecht, cloud scale-ups, managed SOCs. Anti-AI-resume angle.",
    partners: ["NEN", "Dutch SOC-ISAC"],
    cities: ["Amsterdam", "Utrecht"],
  },
  {
    code: "IE",
    name: "Irlande",
    nameEn: "Ireland",
    desk: "AI Act, gouvernance, English HQ européen.",
    law: "Gender Pay Gap + EU pay transparency. Bandes dans l’annonce.",
    lawEn: "Gender Pay Gap reporting + EU pay transparency. Bands in the ad.",
    testCulture: "open",
    testNote: "Dublin recrute la gouvernance IA. L’épreuve « classer un système » est plus crédible qu’un diploma mill.",
    testNoteEn: "Dublin hires AI governance. Classifying a system beats a diploma mill.",
    gtm: "Leads AI Act, ISO 42001. Partenariats notified bodies.",
    gtmEn: "AI Act / ISO 42001 leads. Notified-body partnerships.",
    partners: ["NSAI", "ISO 42001 auditors"],
    cities: ["Dublin"],
  },
  {
    code: "SE",
    name: "Suède",
    nameEn: "Sweden",
    desk: "Climat, kWh, marchés publics. Transparence déjà culturelle.",
    law: "Transparence salariale sociale + UE. Les bandes ne choquent personne.",
    lawEn: "Social + EU pay transparency. Bands shock nobody.",
    testCulture: "mixed",
    testNote: "Consensus suédois : l’épreuve obligatoire peut sembler brutale. La formuler « preuve partagée », pas « filtre ».",
    testNoteEn: "Swedish consensus: a mandatory trial can feel brutal. Frame it as shared proof, not a filter.",
    gtm: "Villes et jumeaux énergétiques. Raconter le kWh, pas le hustle.",
    gtmEn: "Cities and energy twins. Talk kWh, not hustle.",
    partners: ["Energimyndigheten", "CSRD auditors"],
    cities: ["Stockholm"],
  },
  {
    code: "PT",
    name: "Portugal",
    nameEn: "Portugal",
    desk: "Lisbonne remote-first déjà dans Vera (Sable). Hub fuseau ±2h.",
    law: "Directive UE. Salaire publié = avantage, pas un risque.",
    lawEn: "EU directive. Published salary is an advantage, not a risk.",
    testCulture: "open",
    testNote: "Le remote Lisbon a l’habitude des tests async. Garder l’épreuve < 8 min.",
    testNoteEn: "Lisbon remote already sits async tests. Keep the trial under 8 minutes.",
    gtm: "Ancrer Sable / remote Europe. Pas un 2e marché à part.",
    gtmEn: "Anchor on Sable / remote Europe. Not a second separate market.",
    partners: ["Web Summit alumni companies", "PT tech unions"],
    cities: ["Lisbon"],
  },
  {
    code: "GB",
    name: "Royaume-Uni",
    nameEn: "United Kingdom",
    desk: "Concurrentiel. Skills-first déjà mainstream. Différencier la boucle échec → module.",
    law: "Pas de directive UE. Salary in ads se répand (London). Être en avance reste un signal.",
    lawEn: "No EU directive. Salary-in-ads is spreading (London). Being early remains a signal.",
    testCulture: "open",
    testNote: "HackerRank est le réflexe. Vera gagne si l’échec ouvre un module, pas un silence.",
    testNoteEn: "HackerRank is the reflex. Vera wins if failure opens a module, not a void.",
    gtm: "Niche industrial-tech + anti-AI-resume. Pas un clone Indeed UK.",
    gtmEn: "Industrial-tech niche + anti-AI-resume. Not an Indeed UK clone.",
    partners: ["IfATE", "Open Badges UK"],
    cities: ["London", "Manchester"],
  },
  {
    code: "ES",
    name: "Espagne",
    nameEn: "Spain",
    desk: "Remote Madrid / Barcelone, énergie, soin. Plus tard que DE/NL.",
    law: "Transparence salariale UE. Bandes dans l’offre = conformité, pas marketing.",
    lawEn: "EU pay transparency. Bands in the offer = compliance, not marketing.",
    testCulture: "guarded",
    testNote: "Un test avant même de postuler peut sembler agressif. Proposer l’épreuve après un brief, pas avant le premier clic.",
    testNoteEn: "A test before applying can feel aggressive. Offer the trial after a brief, not before the first click.",
    gtm: "Second wave. Partenariats formation + énergie.",
    gtmEn: "Second wave. Training + energy partnerships.",
    partners: ["SEPE", "colegios profesionales"],
    cities: ["Madrid", "Barcelona"],
  },
];

export const COMPETITORS = [
  { name: "HackerRank / Codility", gap: "Gatekeeping pur. L’échec est un silence. Vera ouvre un module et un retry." },
  { name: "LinkedIn Skills", gap: "QCM auto-administré, badge non portable. Pas d’offre, pas de salaire, pas de pacte." },
  { name: "SkillsFound", gap: "Skills-first européen, salaire obligatoire. Pas de boucle épreuve → module → passeport." },
  { name: "SkillProof / AbilityEx", gap: "Vérification isolée. Vera attache le score à la candidature et au PPQC." },
  { name: "Indeed / LinkedIn Jobs", gap: "Volume, CV IA, ghost. Vera vend un dossier tenu." },
] as const;

export const CREDIBILITY = [
  {
    arena: "lockout",
    standard: "NF C18-510 / LOTO",
    reviewer: "Karim D., chef d’atelier Relève (Fos)",
    reviewed: "2026-07",
    n: 214,
    passRate: 61,
    note: "Un cadenas partagé = 0. Revue trimestrielle avec l’atelier.",
  },
  {
    arena: "agents",
    standard: "EU AI Act · traces + garde-fous",
    reviewer: "Sofia P., eval engineer Aether Ops",
    reviewed: "2026-08",
    n: 96,
    passRate: 54,
    note: "Golden set obligatoire. Un agent sans trace échoue, même s’il « marche ».",
  },
  {
    arena: "fhir",
    standard: "HL7 FHIR R4",
    reviewer: "Claire N., product clinique Charité Grid",
    reviewed: "2026-06",
    n: 41,
    passRate: 58,
    note: "Un soignant relit les items. Une feature tuée par un médecin est un succès pédagogique.",
  },
  {
    arena: "finops",
    standard: "FOCUS + AWS CUR",
    reviewer: "Léa B., SRE Nimbus EU",
    reviewed: "2026-08",
    n: 73,
    passRate: 66,
    note: "Le coût unitaire se lit. Un graphe joli sans unité échoue.",
  },
] as const;
