import type { ContractType, GhostRisk, RemoteType, Seniority } from "./types";

export type SeedCompany = {
  slug: string;
  name: string;
  tagline: string;
  about: string;
  industry: string;
  sizeBand: string;
  hqCity: string;
  hqCountry: string;
  website: string;
  foundedYear: number;
  cultureScore: number;
  hiringVelocity: string;
  values: string[];
};

export type SeedJob = {
  companySlug: string;
  slug: string;
  title: string;
  team: string;
  city: string;
  country: string;
  remoteType: RemoteType;
  contract: ContractType;
  seniority: Seniority;
  salaryMin: number;
  salaryMax: number;
  equity: boolean;
  description: string;
  responsibilities: string[];
  requirements: string[];
  nice: string[];
  benefits: string[];
  skills: string[];
  daysAgo: number;
  applicants: number;
  views: number;
  ghostRisk: GhostRisk;
  collection: string;
  pool?: string;
  barriers?: string[];
  tryBuy?: { days: number; dailyPay: number; supervisor: string; startNote: string };
  slots?: { weekday: number; startHour: number; hours: number; city: string; seats: number }[];
};

export const COMPANIES: SeedCompany[] = [
  {
    slug: "lumina",
    name: "Lumina",
    tagline: "On décarbone les villes, pas les slides.",
    about:
      "Lumina conçoit des jumeaux énergétiques pour les métropoles européennes. L’équipe mélange ingénierie climatique, produit et politique publique. Pas de greenwashing interne : chaque feature a un kilowattheure attaché.",
    industry: "Climat",
    sizeBand: "80–200",
    hqCity: "Paris",
    hqCountry: "France",
    website: "https://lumina.example",
    foundedYear: 2019,
    cultureScore: 88,
    hiringVelocity: "fast",
    values: ["Preuve avant récit", "Semaines de 4,5 jours", "Salaire public en interne"],
  },
  {
    slug: "sable",
    name: "Sable",
    tagline: "L’infra que les devs veulent vraiment.",
    about:
      "Sable construit une plateforme d’observabilité pensée pour les équipes de moins de vingt personnes. Open source au cœur, entreprise autour. Remote-first depuis le premier jour.",
    industry: "Outils développeurs",
    sizeBand: "20–50",
    hqCity: "Lisbonne",
    hqCountry: "Portugal",
    website: "https://sable.example",
    foundedYear: 2021,
    cultureScore: 91,
    hiringVelocity: "steady",
    values: ["Async par défaut", "Écriture d’abord", "Pas de réunions le mercredi"],
  },
  {
    slug: "mireille",
    name: "Mireille",
    tagline: "La santé n’est pas un sprint.",
    about:
      "Mireille équipe les hôpitaux de province avec un dossier patient qui ne fait pas honte à ceux qui l’utilisent. Produit lent, régulation réelle, impact mesurable sur le temps soignant.",
    industry: "Santé",
    sizeBand: "200–500",
    hqCity: "Lyon",
    hqCountry: "France",
    website: "https://mireille.example",
    foundedYear: 2016,
    cultureScore: 84,
    hiringVelocity: "steady",
    values: ["Cliniciens dans la room", "Zéro dark pattern", "Congés de recherche"],
  },
  {
    slug: "orbital",
    name: "Orbital",
    tagline: "On vise plus loin que l’orbite.",
    about:
      "Orbital fabrique des systèmes de guidage pour petits lanceurs européens. Culture d’ingénierie dure, documentation obsessionnelle, cantine qui ferme à 19h.",
    industry: "Aérospatial",
    sizeBand: "500–1000",
    hqCity: "Toulouse",
    hqCountry: "France",
    website: "https://orbital.example",
    foundedYear: 2012,
    cultureScore: 79,
    hiringVelocity: "fast",
    values: ["Revue par les pairs", "Sécurité avant deadline", "Apprentissage payé"],
  },
  {
    slug: "atelier-nord",
    name: "Atelier Nord",
    tagline: "Le design comme métier, pas comme slide.",
    about:
      "Studio de produit basé à Copenhague, antenne à Paris. Atelier Nord conçoit des systèmes d’interface pour institutions culturelles et banques qui veulent enfin avoir l’air adultes.",
    industry: "Design",
    sizeBand: "15–40",
    hqCity: "Copenhague",
    hqCountry: "Danemark",
    website: "https://ateliernord.example",
    foundedYear: 2018,
    cultureScore: 93,
    hiringVelocity: "steady",
    values: ["Critique quotidienne", "Pas de junior jetable", "Semaine de 32h l’été"],
  },
  {
    slug: "helios",
    name: "Helios",
    tagline: "La banque, sans le théâtre.",
    about:
      "Helios est une néobanque européenne pour indépendants. Compliance réelle, produit austère, équipe finance + produit qui se parle vraiment. Bureaux à Paris et Londres.",
    industry: "Fintech",
    sizeBand: "200–500",
    hqCity: "Paris",
    hqCountry: "France",
    website: "https://helios.example",
    foundedYear: 2017,
    cultureScore: 76,
    hiringVelocity: "steady",
    values: ["Transparence des bonus", "Pas de titre gonflé", "Astreinte payée double"],
  },
  {
    slug: "maison-vale",
    name: "Maison Vale",
    tagline: "Le luxe, sans le mépris.",
    about:
      "Entreprise familiale devenue groupe. Vale réinternalise sa production numérique après dix ans d’agences. On y parle encore de matière, de saison, et de salaires.",
    industry: "Luxe",
    sizeBand: "1000+",
    hqCity: "Paris",
    hqCountry: "France",
    website: "https://maisonvale.example",
    foundedYear: 1924,
    cultureScore: 71,
    hiringVelocity: "slow",
    values: ["Savoir-faire transmis", "Semaines de collection protégées", "Mutuelle famille"],
  },
  {
    slug: "northline",
    name: "Northline",
    tagline: "Le fret, enfin mesuré.",
    about:
      "Northline orchestre le fret multimodal entre Rotterdam, Anvers et le corridor rhénan. Data, opérations, et un dégoût affiché pour les Excel orphelins.",
    industry: "Logistique",
    sizeBand: "200–500",
    hqCity: "Amsterdam",
    hqCountry: "Pays-Bas",
    website: "https://northline.example",
    foundedYear: 2014,
    cultureScore: 82,
    hiringVelocity: "fast",
    values: ["Ops dans le produit", "Astreinte rotative", "Néerlandais facultatif"],
  },
  {
    slug: "kora",
    name: "Kora",
    tagline: "Le soleil, en kilowatts.",
    about:
      "Kora installe et opère des ombrières solaires sur les parkings du sud de l’Europe. Terrain + logiciel. On embauche des gens qui acceptent de monter sur un toit.",
    industry: "Énergie",
    sizeBand: "50–150",
    hqCity: "Marseille",
    hqCountry: "France",
    website: "https://kora.example",
    foundedYear: 2020,
    cultureScore: 87,
    hiringVelocity: "fast",
    values: ["Terrain un jour par semaine", "Vélo de fonction", "Prime chaleur"],
  },
  {
    slug: "relais",
    name: "Relais",
    tagline: "Le journalisme, payé.",
    about:
      "Relais est une rédaction européenne indépendante. Abonnements, pas de pub programmatique. On y embauche des journalistes, des développeurs, et des gens qui savent compter.",
    industry: "Médias",
    sizeBand: "30–80",
    hqCity: "Bruxelles",
    hqCountry: "Belgique",
    website: "https://relais.example",
    foundedYear: 2015,
    cultureScore: 90,
    hiringVelocity: "frozen",
    values: ["Indépendance éditoriale", "Salaires publiés", "Pas de metric vanity"],
  },
  {
    slug: "releve",
    name: "Relève",
    tagline: "Les machines, pas les PowerPoints.",
    about:
      "Relève tient la maintenance de trois sites industriels à Fos-sur-Mer. Pas de slide, pas de « digitalisation de la GMAO » en copilot. Des équipes de nuit, un parc d’outils neuf, des habilitations payées. On embauche des gens qui savent dire non à une ligne.",
    industry: "Industrie",
    sizeBand: "40–80",
    hqCity: "Fos-sur-Mer",
    hqCountry: "France",
    website: "https://releve.example",
    foundedYear: 2008,
    cultureScore: 89,
    hiringVelocity: "steady",
    values: ["Consignation non négociable", "Outils neufs", "Astreinte écrite"],
  },
  {
    slug: "lise",
    name: "Maison Lise",
    tagline: "Le soin, sans le discours.",
    about:
      "Aide à domicile à Lyon. Cinq personnes par jour, pas neuf. Trajets payés, 13e mois, supervision mensuelle. On refuse les plans d’aide qui ne tiennent pas. Ce n’est pas de la vocation : c’est un métier tenu.",
    industry: "Soin à domicile",
    sizeBand: "25–60",
    hqCity: "Lyon",
    hqCountry: "France",
    website: "https://maisonlise.example",
    foundedYear: 2011,
    cultureScore: 92,
    hiringVelocity: "steady",
    values: ["Plafond de tournée", "Trajets payés", "Supervision réelle"],
  },
];

export const JOBS: SeedJob[] = [
  {
    companySlug: "lumina",
    slug: "product-designer-lumina-paris",
    title: "Product designer",
    team: "Produit villes",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 52000,
    salaryMax: 68000,
    equity: true,
    description:
      "Vous dessinez les interfaces que les urbanistes et les ingénieurs énergétiques utilisent vraiment — pas des maquettes pour un board. L’équipe produit tient en huit personnes. On attend un designer qui sait arbitrer, écrire, et défendre un système plutôt qu’un écran.",
    responsibilities: [
      "Tenir le système d’interface des jumeaux énergétiques",
      "Mener les recherches terrain avec les métropoles clientes",
      "Travailler en binôme avec un PM et deux ingénieurs front",
    ],
    requirements: [
      "4 ans de produit digital, dont un outil métier",
      "Portfolio avec un système, pas seulement des écrans marketing",
      "Français et anglais de travail",
    ],
    nice: ["Expérience secteur public", "Notions d’énergie ou de SIG"],
    benefits: ["Intéressement", "2 jours remote", "Forfait mobilité"],
    skills: ["Figma", "Design system", "Recherche utilisateur", "Produit B2B"],
    daysAgo: 3,
    applicants: 18,
    views: 240,
    ghostRisk: "low",
    collection: "design",
  },
  {
    companySlug: "lumina",
    slug: "data-scientist-climat-lumina",
    title: "Data scientist climat",
    team: "Modèles",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 72000,
    salaryMax: 92000,
    equity: true,
    description:
      "Vous construisez les modèles qui estiment la consommation réelle d’un îlot, pas la moyenne nationale. Données capteurs, cadastre, météo. On publie une partie du travail.",
    responsibilities: [
      "Industrialiser les modèles de charge énergétique",
      "Documenter l’incertitude pour les clients publics",
      "Encadrer un data engineer junior",
    ],
    requirements: [
      "Python et stats solides",
      "Un passage par l’énergie, le climat ou les transports",
      "Goût pour l’écriture technique",
    ],
    nice: ["PyTorch", "PostGIS", "Publication scientifique"],
    benefits: ["Budget conférence", "Télétravail 2j", "Intéressement"],
    skills: ["Python", "Statistiques", "Énergie", "PostGIS"],
    daysAgo: 6,
    applicants: 11,
    views: 190,
    ghostRisk: "low",
    collection: "climat",
  },
  {
    companySlug: "lumina",
    slug: "account-public-lumina",
    title: "Account public",
    team: "Villes",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 58000,
    salaryMax: 74000,
    equity: false,
    description:
      "Vous portez les comptes métropole. Marchés publics, élus, DSI. On cherche quelqu’un qui a déjà perdu un appel d’offres et qui sait pourquoi.",
    responsibilities: [
      "Piloter 6 à 8 comptes collectivités",
      "Écrire les réponses aux marchés avec le produit",
      "Remonter le terrain vers la roadmap",
    ],
    requirements: ["Expérience vente secteur public", "Français natif", "Calme en commission"],
    nice: ["Réseau métropoles", "Anglais négociation"],
    benefits: ["Variable plafonné et écrit", "Titres resto", "Mutuelle famille"],
    skills: ["Vente B2G", "Marchés publics", "Négociation"],
    daysAgo: 9,
    applicants: 7,
    views: 130,
    ghostRisk: "low",
    collection: "public",
  },
  {
    companySlug: "sable",
    slug: "staff-backend-sable",
    title: "Staff backend engineer",
    team: "Runtime",
    city: "Lisbonne",
    country: "Portugal",
    remoteType: "remote",
    contract: "cdi",
    seniority: "staff",
    salaryMin: 90000,
    salaryMax: 120000,
    equity: true,
    description:
      "Vous êtes la personne qui rend le runtime ennuyeux. Ingestion, files, rétention, coût. Remote Europe, fuseau à ±2h de Lisbonne. On écrit beaucoup, on se parle peu.",
    responsibilities: [
      "Tenir l’architecture d’ingestion (Go + Kafka)",
      "Réduire le coût unitaire par événement",
      "Mentorat des mid, sans devenir un manager par défaut",
    ],
    requirements: ["Go ou Rust en production", "Systèmes distribués", "Écriture claire en anglais"],
    nice: ["ClickHouse", "eBPF", "Open source visible"],
    benefits: ["100% remote Europe", "Matériel au choix", "20% open source"],
    skills: ["Go", "Kafka", "Systèmes distribués", "ClickHouse"],
    daysAgo: 2,
    applicants: 24,
    views: 410,
    ghostRisk: "low",
    collection: "staff",
  },
  {
    companySlug: "sable",
    slug: "frontend-sable-remote",
    title: "Frontend engineer",
    team: "Console",
    city: "Lisbonne",
    country: "Portugal",
    remoteType: "remote",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 58000,
    salaryMax: 78000,
    equity: true,
    description:
      "La console Sable est un outil dense. Graphiques, tables, états vides honnêtes. On veut quelqu’un qui aime les performances de rendu autant que la typographie.",
    responsibilities: [
      "Construire les vues d’exploration de logs",
      "Tenir le design system avec le designer unique",
      "Mesurer le TTI, pas seulement le Lighthouse de la landing",
    ],
    requirements: ["React et TypeScript", "Un outil interne ou data au portfolio", "Remote autonome"],
    nice: ["Canvas / WebGL", "TanStack Table", "Accessibilité"],
    benefits: ["Remote", "Congés illimités encadrés", "Budget home office"],
    skills: ["React", "TypeScript", "Performance", "Design system"],
    daysAgo: 5,
    applicants: 31,
    views: 520,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "sable",
    slug: "developer-advocate-sable",
    title: "Developer advocate",
    team: "Communauté",
    city: "Lisbonne",
    country: "Portugal",
    remoteType: "remote",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 54000,
    salaryMax: 70000,
    equity: true,
    description:
      "Pas un rôle de stand. Vous écrivez, vous répondez, vous cassez le produit avant les clients. Deux conférences par an, pas dix.",
    responsibilities: [
      "Tenir la doc et les guides de démarrage",
      "Faire remonter les issues GitHub vers le produit",
      "Animer l’office hours mensuel",
    ],
    requirements: ["Avoir déjà maintenu un projet public", "Écriture technique", "Anglais courant"],
    nice: ["Vidéo", "Allemand ou français"],
    benefits: ["Remote", "Budget conférence", "Open source company time"],
    skills: ["Documentation", "Communauté", "Developer experience"],
    daysAgo: 12,
    applicants: 16,
    views: 280,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "mireille",
    slug: "product-manager-mireille",
    title: "Product manager hôpital",
    team: "Dossier patient",
    city: "Lyon",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 68000,
    salaryMax: 84000,
    equity: false,
    description:
      "Vous pilotez le module prescriptions. Les utilisateurs sont des internes fatigués et des pharmaciens méfiants. La moindre ambiguïté coûte du temps de soin.",
    responsibilities: [
      "Écrire les specs avec les référents cliniques",
      "Arbitrer dette, conformité et vitesse",
      "Mesurer le temps soignant récupéré",
    ],
    requirements: ["5 ans de PM outil métier", "À l’aise à l’hôpital", "Français impeccable"],
    nice: ["Interop HL7 / FHIR", "Certification HDS"],
    benefits: ["13e mois", "Télétravail 2j", "Compte épargne-temps"],
    skills: ["Product management", "Santé", "FHIR", "Recherche utilisateur"],
    daysAgo: 4,
    applicants: 9,
    views: 160,
    ghostRisk: "low",
    collection: "sante",
  },
  {
    companySlug: "mireille",
    slug: "infirmier-produit-mireille",
    title: "Infirmier·ère produit",
    team: "Clinique",
    city: "Lyon",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 42000,
    salaryMax: 52000,
    equity: false,
    description:
      "Vous restez soignant, vous devenez la voix du service dans le produit. Un jour par semaine en service, le reste avec l’équipe produit. Ce n’est pas un rôle de « ambassadeur » marketing.",
    responsibilities: [
      "Observer les usages en service",
      "Écrire les parcours métier",
      "Former les référents établissements",
    ],
    requirements: ["Diplôme infirmier et 3 ans de service", "Goût pour l’écrit", "Pédagogie"],
    nice: ["Expérience DPI", "Formation"],
    benefits: ["Maintien des primes de dimanche si vacation", "Mutuelle", "Formation financée"],
    skills: ["Soins", "Produit", "Formation", "Observation"],
    daysAgo: 8,
    applicants: 14,
    views: 210,
    ghostRisk: "low",
    collection: "sante",
  },
  {
    companySlug: "mireille",
    slug: "stage-data-mireille",
    title: "Stage data clinique",
    team: "Data",
    city: "Lyon",
    country: "France",
    remoteType: "onsite",
    contract: "stage",
    seniority: "junior",
    salaryMin: 14000,
    salaryMax: 16000,
    equity: false,
    description:
      "Six mois pour nettoyer, documenter et visualiser les indicateurs de charge des services. Encadrement réel, pas une machine à café.",
    responsibilities: [
      "Construire un tableau de charge par service",
      "Documenter les sources",
      "Présenter aux chefs de pôle",
    ],
    requirements: ["Master data / santé en cours", "SQL", "Discrétion"],
    nice: ["R", "Expérience hôpital"],
    benefits: ["Gratification haute fourchette", "Titres resto", "Embauche possible"],
    skills: ["SQL", "Data viz", "Santé"],
    daysAgo: 1,
    applicants: 22,
    views: 300,
    ghostRisk: "low",
    collection: "premier",
  },
  {
    companySlug: "orbital",
    slug: "ingenieur-guidage-orbital",
    title: "Ingénieur guidage",
    team: "GNC",
    city: "Toulouse",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 62000,
    salaryMax: 80000,
    equity: false,
    description:
      "Vous concevez les lois de guidage des étages supérieurs. MATLAB, C, bancs. On ne cherche pas un profil « space enthusiast » : on cherche quelqu’un qui a déjà livré un système critique.",
    responsibilities: [
      "Spécifier et valider les lois GNC",
      "Tenir la revue de vol",
      "Former deux ingénieurs mid",
    ],
    requirements: ["GNC en aéro ou défense", "C ou Ada", "Habilitation possible"],
    nice: ["Simulation 6DDL", "Python scientifique"],
    benefits: ["Intéressement", "Comité d’entreprise réel", "Horaires de site"],
    skills: ["GNC", "C", "Simulation", "Systèmes critiques"],
    daysAgo: 7,
    applicants: 6,
    views: 140,
    ghostRisk: "low",
    collection: "hardtech",
  },
  {
    companySlug: "orbital",
    slug: "alternance-qualite-orbital",
    title: "Alternance qualité logiciel",
    team: "Qualité",
    city: "Toulouse",
    country: "France",
    remoteType: "onsite",
    contract: "alternance",
    seniority: "junior",
    salaryMin: 18000,
    salaryMax: 22000,
    equity: false,
    description:
      "Deux ans pour apprendre la qualité logicielle sur un système de vol. Encadrement par une responsable qualité, pas par un stagiaire de l’année précédente.",
    responsibilities: [
      "Tenir les matrices de tests",
      "Participer aux revues",
      "Rédiger les écarts",
    ],
    requirements: ["École d’ingé ou master qualité", "Rigueur documentaire", "Présence site"],
    nice: ["DO-178", "Python"],
    benefits: ["Gratification convention", "Cantine", "Embauche fréquente"],
    skills: ["Qualité logiciel", "Documentation", "Tests"],
    daysAgo: 11,
    applicants: 19,
    views: 250,
    ghostRisk: "low",
    collection: "premier",
  },
  {
    companySlug: "orbital",
    slug: "tech-lead-embarque-orbital",
    title: "Tech lead embarqué",
    team: "Calculateur",
    city: "Toulouse",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "lead",
    salaryMin: 78000,
    salaryMax: 98000,
    equity: false,
    description:
      "Vous tenez l’équipe calculateur (neuf personnes). Moins de slides, plus de revues de code et de banc. Le titre de lead ici veut dire responsabilité, pas un bureau.",
    responsibilities: [
      "Arbitrer l’architecture du calculateur",
      "Recruter deux profils cette année",
      "Parler vrai aux programmes",
    ],
    requirements: ["Embarqué critique", "Déjà lead ou staff", "Français + anglais"],
    nice: ["RTOS", "FPGA"],
    benefits: ["Voiture de fonction optionnelle", "Intéressement", "Temps partiel accepté"],
    skills: ["Embarqué", "Leadership", "C", "RTOS"],
    daysAgo: 14,
    applicants: 8,
    views: 180,
    ghostRisk: "low",
    collection: "staff",
  },
  {
    companySlug: "atelier-nord",
    slug: "designer-systeme-atelier-nord",
    title: "Designer système",
    team: "Atelier",
    city: "Copenhague",
    country: "Danemark",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 64000,
    salaryMax: 82000,
    equity: false,
    description:
      "Vous tenez le système d’interface du studio — tokens, typographie, composants, critique. Une semaine par mois à Paris. On paie le relogement d’essai de trois mois.",
    responsibilities: [
      "Maintenir le système multi-clients",
      "Critiquer le travail des mid",
      "Écrire les règles, pas seulement les Figma",
    ],
    requirements: ["Système en production", "Typographie réelle", "Anglais courant"],
    nice: ["Danois", "Code front de base"],
    benefits: ["Semaine de 37h", "Août à 32h", "Relogement d’essai"],
    skills: ["Design system", "Typographie", "Figma", "Critique"],
    daysAgo: 4,
    applicants: 13,
    views: 220,
    ghostRisk: "low",
    collection: "design",
  },
  {
    companySlug: "atelier-nord",
    slug: "stage-design-atelier-nord",
    title: "Stage design produit",
    team: "Atelier",
    city: "Paris",
    country: "France",
    remoteType: "onsite",
    contract: "stage",
    seniority: "junior",
    salaryMin: 14000,
    salaryMax: 16000,
    equity: false,
    description:
      "Un stage de six mois dans un vrai atelier. Vous assistez aux critiques, vous produisez, on vous dit quand c’est mauvais. C’est le point.",
    responsibilities: [
      "Produire des explorations sous direction",
      "Documenter les décisions",
      "Tenir la bibliothèque d’icônes d’un client",
    ],
    requirements: ["École de design ou équivalent", "Portfolio honnête", "Présence Paris"],
    nice: ["Intérêt pour l’édition"],
    benefits: ["Gratification", "Matériel", "Possibilité d’embauche"],
    skills: ["Figma", "Édition", "Icônes"],
    daysAgo: 2,
    applicants: 41,
    views: 610,
    ghostRisk: "low",
    collection: "premier",
  },
  {
    companySlug: "helios",
    slug: "risk-analyst-helios",
    title: "Risk analyst",
    team: "Crédit",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 56000,
    salaryMax: 70000,
    equity: false,
    description:
      "Vous construisez les règles de crédit pour les indépendants. Moins de scoring magique, plus de cas. On publie le taux d’erreur en interne chaque mois.",
    responsibilities: [
      "Tenir le moteur de règles",
      "Investiguer les faux positifs",
      "Parler aux ops fraude",
    ],
    requirements: ["Crédit ou fraude", "SQL", "Calme sous revue ACPR"],
    nice: ["Python", "Droit conso"],
    benefits: ["Variable écrit", "RTT", "Compte titres d’entreprise"],
    skills: ["Risque", "SQL", "Crédit", "Fraude"],
    daysAgo: 6,
    applicants: 12,
    views: 200,
    ghostRisk: "low",
    collection: "finance",
  },
  {
    companySlug: "helios",
    slug: "backend-kotlin-helios",
    title: "Backend Kotlin",
    team: "Ledger",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 70000,
    salaryMax: 90000,
    equity: true,
    description:
      "Le ledger n’a pas le droit d’être approximatif. Kotlin, Postgres, audits. Vous aimez les invariants plus que les frameworks.",
    responsibilities: [
      "Faire évoluer le journal comptable",
      "Tenir les migrations sans downtime",
      "Écrire les runbooks",
    ],
    requirements: ["Kotlin ou Java en production finance", "SQL avancé", "Culture de revue"],
    nice: ["Event sourcing", "Kafka"],
    benefits: ["BSPCE", "2j remote", "Astreinte payée"],
    skills: ["Kotlin", "Postgres", "Finance", "Event sourcing"],
    daysAgo: 10,
    applicants: 15,
    views: 270,
    ghostRisk: "low",
    collection: "finance",
  },
  {
    companySlug: "helios",
    slug: "freelance-aml-helios",
    title: "Freelance conformité AML",
    team: "Compliance",
    city: "Londres",
    country: "Royaume-Uni",
    remoteType: "remote",
    contract: "freelance",
    seniority: "senior",
    salaryMin: 152000,
    salaryMax: 196000,
    equity: false,
    description:
      "Mission de quatre mois pour durcir le dispositif AML avant un agrément. TJM 700–900 € (152–196 k€ annualisés), annoncé, pas « selon profil ». Remote, quelques jours à Paris.",
    responsibilities: [
      "Cartographier les scénarios",
      "Écrire les procédures",
      "Former l’équipe ops",
    ],
    requirements: ["AML établissement", "Anglais rédactionnel", "Disponible sous 3 semaines"],
    nice: ["FCA", "Français"],
    benefits: ["TJM publié", "Facturation 30 jours", "Matériel fourni"],
    skills: ["AML", "Conformité", "Procédures"],
    daysAgo: 3,
    applicants: 9,
    views: 150,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "maison-vale",
    slug: "directeur-digital-vale",
    title: "Directeur digital",
    team: "Direction",
    city: "Paris",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "lead",
    salaryMin: 110000,
    salaryMax: 140000,
    equity: false,
    description:
      "Vous rapatriez le digital après une décennie d’agences. Politique interne réelle, budget réel, attente de résultats en deux saisons. Ce n’est pas un rôle de transformation en kit.",
    responsibilities: [
      "Recruter l’équipe produit interne (8 personnes)",
      "Couper les contrats agence inutiles",
      "Aligner e-com, retail et création",
    ],
    requirements: ["Direction digitale luxe ou retail", "Recrutement d’équipe", "Français natif"],
    nice: ["Italien", "Expérience ERP retail"],
    benefits: ["Intéressement groupe", "Remises salariés", "Comité de direction"],
    skills: ["Leadership", "E-commerce", "Luxe", "Recrutement"],
    daysAgo: 18,
    applicants: 11,
    views: 340,
    ghostRisk: "medium",
    collection: "staff",
  },
  {
    companySlug: "maison-vale",
    slug: "ux-writer-vale",
    title: "UX writer",
    team: "Langue",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 46000,
    salaryMax: 58000,
    equity: false,
    description:
      "Vous tenez la voix numérique de l’entreprise : checkout, SAV, newsletter. On veut moins de « exclusif », plus de clarté. Le français d’abord, l’anglais ensuite.",
    responsibilities: [
      "Écrire tous les microcopy critiques",
      "Tenir le guide de voix",
      "Travailler avec le juridique",
    ],
    requirements: ["Écriture produit", "Français d’édition", "Goût du détail"],
    nice: ["Italien", "Accessibilité éditoriale"],
    benefits: ["Remises", "RTT", "Bibliothèque interne"],
    skills: ["UX writing", "Édition", "Français", "Accessibilité"],
    daysAgo: 5,
    applicants: 20,
    views: 260,
    ghostRisk: "low",
    collection: "design",
  },
  {
    companySlug: "northline",
    slug: "ops-research-northline",
    title: "Operations research",
    team: "Réseau",
    city: "Amsterdam",
    country: "Pays-Bas",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 74000,
    salaryMax: 96000,
    equity: true,
    description:
      "Vous optimisez le réseau multimodal. Solveurs, contraintes portuaires, grèves, marées. Le modèle qui ignore le réel ne passe pas la revue.",
    responsibilities: [
      "Tenir le moteur d’affectation",
      "Expliquer les arbitrages aux ops",
      "Publier les hypothèses",
    ],
    requirements: ["OR ou maths appliquées", "Python", "Anglais de travail"],
    nice: ["Néerlandais", "Expérience portuaire"],
    benefits: ["Visa sponsorisé", "Vélo + OV", "BSPCE"],
    skills: ["Recherche opérationnelle", "Python", "Optimisation", "Logistique"],
    daysAgo: 4,
    applicants: 7,
    views: 170,
    ghostRisk: "low",
    collection: "hardtech",
  },
  {
    companySlug: "northline",
    slug: "product-ops-northline",
    title: "Product operations",
    team: "Produit",
    city: "Amsterdam",
    country: "Pays-Bas",
    remoteType: "remote",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 56000,
    salaryMax: 72000,
    equity: true,
    description:
      "Vous rendez le produit utilisable par les dispatchers de Rotterdam à Bâle. Specs, formation, tickets. Remote Europe, une semaine par trimestre à Amsterdam.",
    responsibilities: [
      "Tenir le backlog ops",
      "Écrire les guides de dispatch",
      "Mesurer l’adoption réelle",
    ],
    requirements: ["Produit ou ops transport", "Écriture", "Autonomie remote"],
    nice: ["Allemand", "SQL"],
    benefits: ["Remote Europe", "Travel budget", "BSPCE"],
    skills: ["Product operations", "Logistique", "Documentation"],
    daysAgo: 8,
    applicants: 10,
    views: 190,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "kora",
    slug: "chef-projet-solaire-kora",
    title: "Chef de projet solaire",
    team: "Terrain",
    city: "Marseille",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 44000,
    salaryMax: 56000,
    equity: false,
    description:
      "Vous livrez des ombrières. Permis, sous-traitance, planning, clients collectivités. Il faut aimer le terrain et détester les reports flous.",
    responsibilities: [
      "Piloter 4 à 6 chantiers simultanés",
      "Tenir les relations mairie / bailleur",
      "Remonter les écarts au bureau d’études",
    ],
    requirements: ["Chantier ENR ou BTP", "Permis B", "Français"],
    nice: ["Habilitation électrique", "Occitan facultatif"],
    benefits: ["Véhicule", "Prime chaleur", "Intéressement"],
    skills: ["Gestion de projet", "Solaire", "Collectivités", "Chantier"],
    daysAgo: 3,
    applicants: 17,
    views: 230,
    ghostRisk: "low",
    collection: "climat",
  },
  {
    companySlug: "kora",
    slug: "full-stack-kora",
    title: "Full-stack monitoring",
    team: "Logiciel",
    city: "Marseille",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 48000,
    salaryMax: 64000,
    equity: true,
    description:
      "Vous construisez l’outil qui dit si une ombrière produit ce qu’elle doit. TypeScript, cartes, alertes. Un jour par semaine sur un site, obligatoire.",
    responsibilities: [
      "Construire le tableau de production",
      "Brancher les onduleurs",
      "Alerter avant le client",
    ],
    requirements: ["TypeScript", "APIs métier", "Goût du terrain"],
    nice: ["Influx / Timescale", "Électrotechnique de base"],
    benefits: ["BSPCE", "1j terrain", "Vélo de fonction"],
    skills: ["TypeScript", "React", "Time series", "Énergie"],
    daysAgo: 6,
    applicants: 13,
    views: 200,
    ghostRisk: "low",
    collection: "climat",
  },
  {
    companySlug: "kora",
    slug: "alternance-commercial-kora",
    title: "Alternance développement collectivités",
    team: "Commercial",
    city: "Marseille",
    country: "France",
    remoteType: "hybrid",
    contract: "alternance",
    seniority: "junior",
    salaryMin: 16000,
    salaryMax: 20000,
    equity: false,
    description:
      "Vous apprenez à vendre du solaire à des villes, pas à des slides. Encadrement par la responsable grands comptes. Permis B indispensable.",
    responsibilities: [
      "Préparer les dossiers de consultation",
      "Accompagner les visites de site",
      "Tenir le CRM à jour — vraiment",
    ],
    requirements: ["École commerce ou éco", "Permis B", "Aisance orale"],
    nice: ["Stage collectivité"],
    benefits: ["Véhicule partagé", "Embauche visée"],
    skills: ["Vente", "Collectivités", "CRM"],
    daysAgo: 9,
    applicants: 21,
    views: 280,
    ghostRisk: "low",
    collection: "premier",
  },
  {
    companySlug: "relais",
    slug: "journaliste-data-relais",
    title: "Journaliste data",
    team: "Enquête",
    city: "Bruxelles",
    country: "Belgique",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 42000,
    salaryMax: 54000,
    equity: false,
    description:
      "Annonce encore en ligne. Relais a gelé ses embauches après un trou de trésorerie au printemps. L’offre n’a pas été retirée. Vera la signale.",
    responsibilities: [
      "Enquêter à partir de données publiques",
      "Travailler avec un développeur",
      "Publier sous double lecture",
    ],
    requirements: ["Journalisme data", "SQL ou R", "Français + anglais"],
    nice: ["Néerlandais", "Scraping"],
    benefits: ["Salaires publiés en interne", "Pas de pub"],
    skills: ["Journalisme", "SQL", "Enquête", "Data viz"],
    daysAgo: 68,
    applicants: 4,
    views: 890,
    ghostRisk: "high",
    collection: "medias",
  },
  {
    companySlug: "relais",
    slug: "dev-edito-relais",
    title: "Développeur·se éditorial",
    team: "Tech",
    city: "Bruxelles",
    country: "Belgique",
    remoteType: "remote",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 50000,
    salaryMax: 64000,
    equity: false,
    description:
      "Même gel. L’annonce sert encore à collecter des CV « au cas où ». On vous le dit ici, pas après trois tours.",
    responsibilities: [
      "Tenir le site et les outils d’enquête",
      "Aider les journalistes à publier des pièces interactives",
    ],
    requirements: ["TypeScript", "Goût du texte", "Remote Europe"],
    nice: ["Svelte", "Cartographie"],
    benefits: ["Remote", "Matériel"],
    skills: ["TypeScript", "Journalisme", "Svelte"],
    daysAgo: 72,
    applicants: 3,
    views: 640,
    ghostRisk: "high",
    collection: "medias",
  },
  {
    companySlug: "lumina",
    slug: "stage-produit-lumina",
    title: "Stage produit climat",
    team: "Produit",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "stage",
    seniority: "junior",
    salaryMin: 14000,
    salaryMax: 16000,
    equity: false,
    description:
      "Vous assistez la PM villes pendant six mois. Specs, terrain, mesure. Encadrement hebdomadaire écrit. On embauche souvent.",
    responsibilities: [
      "Préparer les entretiens usagers",
      "Tenir le journal de décision",
      "Aider au recettage",
    ],
    requirements: ["École produit / ingénieur / sciences po", "Écriture", "Curiosité énergie"],
    nice: ["SIG", "Anglais"],
    benefits: ["Gratification", "Titres resto", "Embauche fréquente"],
    skills: ["Produit", "Recherche utilisateur", "Écriture"],
    daysAgo: 2,
    applicants: 28,
    views: 360,
    ghostRisk: "low",
    collection: "premier",
  },
  {
    companySlug: "sable",
    slug: "security-engineer-sable",
    title: "Security engineer",
    team: "Platform",
    city: "Lisbonne",
    country: "Portugal",
    remoteType: "remote",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 85000,
    salaryMax: 110000,
    equity: true,
    description:
      "Vous êtes le premier security hire. Programme, pas théâtre. Remote, fuseau Europe. On attend un plan à 90 jours, pas un audit PowerPoint.",
    responsibilities: [
      "Tenir le programme AppSec",
      "Revoir l’infra d’ingestion",
      "Répondre aux questionnaires sans mentir",
    ],
    requirements: ["AppSec produit SaaS", "Cloud", "Écriture claire"],
    nice: ["SOC2 déjà mené", "Go"],
    benefits: ["Remote", "On-call rare et payé", "BSPCE"],
    skills: ["Sécurité", "AppSec", "Cloud", "Go"],
    daysAgo: 7,
    applicants: 11,
    views: 210,
    ghostRisk: "low",
    collection: "remote",
  },
  {
    companySlug: "helios",
    slug: "designer-produit-helios",
    title: "Product designer finance",
    team: "Produit",
    city: "Paris",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 62000,
    salaryMax: 80000,
    equity: true,
    description:
      "Vous concevez les flux les plus sensibles : crédit, opposition, clôture. L’esthétique est austère. La clarté est non négociable.",
    responsibilities: [
      "Tenir les parcours réglementés",
      "Tester avec de vrais indépendants",
      "Travailler avec le juridique dès le wireframe",
    ],
    requirements: ["Produit finance ou admin", "Portfolio de flux complexes", "Français"],
    nice: ["Accessibilité", "Recherche solo"],
    benefits: ["BSPCE", "2j remote", "Mutuelle famille"],
    skills: ["Figma", "Produit B2B", "Finance", "Accessibilité"],
    daysAgo: 13,
    applicants: 16,
    views: 290,
    ghostRisk: "low",
    collection: "design",
  },
  {
    companySlug: "northline",
    slug: "data-engineer-northline",
    title: "Data engineer",
    team: "Plateforme",
    city: "Amsterdam",
    country: "Pays-Bas",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 62000,
    salaryMax: 78000,
    equity: true,
    description:
      "Vous rendez les événements de fret fiables. Kafka, dbt, entrepôt. Les ops doivent pouvoir croire le chiffre le lundi matin.",
    responsibilities: [
      "Tenir les pipelines critiques",
      "Documenter les contrats de données",
      "Réduire les jobs qui cassent le week-end",
    ],
    requirements: ["Pipelines en production", "SQL", "Anglais"],
    nice: ["dbt", "Kafka", "Airflow"],
    benefits: ["Visa", "BSPCE", "OV-chipkaart"],
    skills: ["dbt", "SQL", "Kafka", "Python"],
    daysAgo: 5,
    applicants: 14,
    views: 240,
    ghostRisk: "low",
    collection: "hardtech",
  },
  {
    companySlug: "maison-vale",
    slug: "cdi-retail-ops-vale",
    title: "Retail operations",
    team: "Réseau",
    city: "Paris",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 42000,
    salaryMax: 52000,
    equity: false,
    description:
      "Vous tenez l’excellence opérationnelle des boutiques françaises. L’annonce est ancienne, le siège est lent : on signale un délai probable.",
    responsibilities: [
      "Auditer les process caisse et stock",
      "Former les responsables de boutique",
      "Remonter les irritants au digital",
    ],
    requirements: ["Retail luxe ou premium", "Déplacements France", "Français"],
    nice: ["Italien", "Excel avancé"],
    benefits: ["Remises", "Mutuelle", "Prime vacances"],
    skills: ["Retail", "Opérations", "Formation"],
    daysAgo: 41,
    applicants: 6,
    views: 410,
    ghostRisk: "medium",
    collection: "luxe",
  },
  {
    companySlug: "releve",
    slug: "technicien-maintenance-releve",
    title: "Technicien de maintenance",
    team: "Ligne 2",
    city: "Fos-sur-Mer",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 34000,
    salaryMax: 40000,
    equity: false,
    description:
      "Vous tenez la presse et le quai. Pannes, rondes, consignations. En trois ans, le poste mène à chef d’équipe — CACES et BR payés par l’entreprise. Ce n’est pas un job d’intérim déguisé.",
    responsibilities: [
      "Rondes et pannes sur la ligne 2",
      "Consignation et préparation des kits atelier",
      "Former un apprenti dès la première année",
    ],
    requirements: ["Maintenance industrielle 2 ans min.", "CACES 3 ou à passer sous 90 jours", "Habilitation BS"],
    nice: ["Hydraulique", "GMAO"],
    benefits: ["Mutuelle 70 % famille", "1 800 € formation / an", "Prime bruit 180 €", "Astreinte 1/6 majorée"],
    skills: ["Mécanique", "Hydraulique", "Consignation", "GMAO"],
    daysAgo: 2,
    applicants: 9,
    views: 140,
    ghostRisk: "low",
    collection: "terrain",
  },
  {
    companySlug: "kora",
    slug: "electricien-ombrieres-kora",
    title: "Électricien ombrières",
    team: "Mise en service",
    city: "Marseille",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 36000,
    salaryMax: 44000,
    equity: false,
    description:
      "Vous câblez, vous mettez en service, vous recevez Enedis. Parking, hauteur, chaleur. Habilitation B2V/BR payée. En août on s’arrête à 13h — c’est écrit.",
    responsibilities: [
      "Câblage DC/AC des ombrières",
      "Mise en service onduleurs et tests d’isolement",
      "Réception avec le chef de projet",
    ],
    requirements: ["Électricien chantier ou industrie", "Habilitation B1V min. (B2V/BR financée)", "Travail en hauteur"],
    nice: ["IRVE", "CACES nacelle"],
    benefits: ["Habilitations internes", "Prime chaleur 200 €", "Véhicule chantier", "Mutuelle 60 % famille"],
    skills: ["Électricité", "Onduleurs", "Chantier", "Habilitation"],
    daysAgo: 1,
    applicants: 11,
    views: 160,
    ghostRisk: "low",
    collection: "terrain",
  },
  {
    companySlug: "lise",
    slug: "aide-domicile-lise",
    title: "Auxiliaire de vie à domicile",
    team: "Secteur 8e / 3e",
    city: "Lyon",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 26000,
    salaryMax: 30000,
    equity: false,
    description:
      "Cinq personnes par jour, pas neuf. Trajets payés. 13e mois. Vous refusez un plan qui ne tient pas — la coordinatrice le dit avec vous. Ce n’est pas de la vocation vendue.",
    responsibilities: [
      "Toilettes, repas, présence chez cinq personnes",
      "Transmissions écrites à l’infirmière",
      "Signalement des changements, sans jugement",
    ],
    requirements: ["DEAES ou 2 ans d’expérience", "Permis B", "Lyon et proche"],
    nice: ["Formation Alzheimer", "SST"],
    benefits: ["13e mois", "Trajets payés", "Mutuelle 80 % famille", "Supervision mensuelle"],
    skills: ["Soin", "Présence", "Transmission", "Manutention"],
    daysAgo: 3,
    applicants: 8,
    views: 120,
    ghostRisk: "low",
    collection: "terrain",
  },
  {
    companySlug: "northline",
    slug: "business-developer-asie-northline",
    title: "Business developer Asie",
    team: "Corridor",
    city: "Amsterdam",
    country: "Pays-Bas",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 78000,
    salaryMax: 98000,
    equity: true,
    description:
      "Vous ouvrez le corridor Asie–Europe : chargeurs, transitaires, douanes. Mandarin de négociation, pas de cocktail. Le « maybe » n’est pas un oui. Fuseau SGT tenu. On embauche quelqu’un qui a déjà perdu un deal à Shanghai et qui sait pourquoi.",
    responsibilities: [
      "Ouvrir 6 à 8 comptes chargeurs Asie du Nord-Est",
      "Tenir les négociations avec un intermédiaire local quand la face l’exige",
      "Écrire les accords — jamais un pouce emoji",
    ],
    requirements: [
      "Mandarin de négo (HSK 5 min. ou natif)",
      "3 ans de corridor Asie–Europe freight ou industrie",
      "Anglais d’arbitrage, néerlandais facultatif",
    ],
    nice: ["Japonais", "Douane / Incoterms", "Réseau Shanghai / Shenzhen nommé"],
    benefits: ["Visa NL", "Travel Asie trimestriel", "BSPCE", "Fuseau respecté — pas d’agenda caché 23 h"],
    skills: ["Mandarin", "Guanxi", "Négociation", "Freight", "Incoterms"],
    daysAgo: 2,
    applicants: 4,
    views: 190,
    ghostRisk: "low",
    collection: "staff",
  },
];
