import type { SeedCompany, SeedJob } from "./seed-data";

export const GEO_COMPANIES: SeedCompany[] = [
  {
    slug: "armor-volt",
    name: "Armor Volt",
    tagline: "Ombrières en Bretagne, pas des slides ENR.",
    about: "Armor Volt pose des ombrières et du résidentiel PV autour de Rennes. Habilitations internes, formation OPCO écrite.",
    industry: "Énergie",
    sizeBand: "20–80",
    hqCity: "Rennes",
    hqCountry: "France",
    website: "https://armor-volt.example",
    foundedYear: 2018,
    cultureScore: 84,
    hiringVelocity: "fast",
    values: ["B2V payé", "Prime humidité", "Pacte 8 jours"],
  },
  {
    slug: "loire-chaleur",
    name: "Loire Chaleur",
    tagline: "PAC et chaudières. Le geste, pas le devis magique.",
    about: "Nantes et Saint-Nazaire. Plombiers-chauffagistes, PAC, entretien. Reprise d’un atelier en cours.",
    industry: "Bâtiment",
    sizeBand: "15–60",
    hqCity: "Nantes",
    hqCountry: "France",
    website: "https://loire-chaleur.example",
    foundedYear: 1998,
    cultureScore: 82,
    hiringVelocity: "steady",
    values: ["Astreinte écrite", "Véhicule", "Tutorat 6 mois"],
  },
  {
    slug: "flandre-soin",
    name: "Flandre Soin",
    tagline: "CHU et Ehpad. Un soignant nommé, pas un pool.",
    about: "Lille, Roubaix, Tourcoing. Aides-soignants, immersions RSA payées, garde d’enfants partenaire.",
    industry: "Santé",
    sizeBand: "200–800",
    hqCity: "Lille",
    hqCountry: "France",
    website: "https://flandre-soin.example",
    foundedYear: 2012,
    cultureScore: 80,
    hiringVelocity: "fast",
    values: ["Try & Buy payé", "Prime dimanche écrite", "Plafond de patients"],
  },
  {
    slug: "rhin-atome",
    name: "Rhin Atome",
    tagline: "Maintenance nucléaire. Habilitation, pas un slogan.",
    about: "Strasbourg / Fessenheim / Cattenom. Techniciens habilités, astreinte 1/6, allemand de consigne bienvenu.",
    industry: "Énergie",
    sizeBand: "80–250",
    hqCity: "Strasbourg",
    hqCountry: "France",
    website: "https://rhin-atome.example",
    foundedYear: 2006,
    cultureScore: 86,
    hiringVelocity: "steady",
    values: ["Habilitation interne", "Cantine 19 h", "Pacte 10 jours"],
  },
  {
    slug: "garonne-toits",
    name: "Garonne Toits",
    tagline: "Couverture. La hauteur, écrite.",
    about: "Bordeaux et gironde. Couvreurs, zingueurs, ardoises. Cédant à 61 ans, parcours reprise ouvert.",
    industry: "Bâtiment",
    sizeBand: "8–40",
    hqCity: "Bordeaux",
    hqCountry: "France",
    website: "https://garonne-toits.example",
    foundedYear: 1987,
    cultureScore: 79,
    hiringVelocity: "steady",
    values: ["Harnais neuf", "Jours pluie payés", "Reprise tutorée"],
  },
  {
    slug: "alpes-chantier",
    name: "Alpes Chantier",
    tagline: "Conducteurs de travaux. Le planning tient, ou on le dit le jour même.",
    about: "Grenoble, Isère. BTP, collèges, ombrières. Pas de closer qui vit au mois.",
    industry: "Bâtiment",
    sizeBand: "40–120",
    hqCity: "Grenoble",
    hqCountry: "France",
    website: "https://alpes-chantier.example",
    foundedYear: 2001,
    cultureScore: 81,
    hiringVelocity: "fast",
    values: ["Retard dit le jour même", "Véhicule", "Astreinte non"],
  },
  {
    slug: "midi-soin",
    name: "Midi Soin",
    tagline: "Domicile Montpellier. Cinq personnes, pas neuf.",
    about: "Hérault. Auxiliaires, DEAES, trajets payés. Matrice RSA (garde, mobilité).",
    industry: "Soin",
    sizeBand: "30–90",
    hqCity: "Montpellier",
    hqCountry: "France",
    website: "https://midi-soin.example",
    foundedYear: 2016,
    cultureScore: 83,
    hiringVelocity: "fast",
    values: ["Plafond 5", "Trajets", "Supervision"],
  },
  {
    slug: "finistere-routes",
    name: "Finistère Routes",
    tagline: "Transport technique. SPL, pas de l’Uber camouflé.",
    about: "Brest, Quimper. Conducteurs SPL, planning figé 4 semaines, pas de dimanche surprise.",
    industry: "Transport",
    sizeBand: "50–150",
    hqCity: "Brest",
    hqCountry: "France",
    website: "https://finistere-routes.example",
    foundedYear: 1994,
    cultureScore: 78,
    hiringVelocity: "steady",
    values: ["Planning figé", "Heures sup payées", "Véhicule relais"],
  },
];

function job(
  partial: Omit<SeedJob, "equity" | "ghostRisk" | "daysAgo" | "applicants" | "views" | "nice"> & Partial<Pick<SeedJob, "equity" | "ghostRisk" | "daysAgo" | "applicants" | "views" | "nice" | "pool">>,
): SeedJob {
  return {
    equity: false,
    ghostRisk: "low",
    daysAgo: 4,
    applicants: 6,
    views: 90,
    nice: [],
    ...partial,
  };
}

export const GEO_JOBS: SeedJob[] = [
  job({
    companySlug: "armor-volt",
    slug: "electricien-pv-armor-volt",
    title: "Électricien photovoltaïque",
    team: "Chantier 35",
    city: "Rennes",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 32000,
    salaryMax: 38000,
    description: "Ombrières et toitures Rennes / Ille-et-Vilaine. B2V interne, formation OPCO. Épreuve schéma dans l’offre.",
    responsibilities: ["Pose onduleurs et chemins de câbles", "Mise en service", "SAV 48 h"],
    requirements: ["Électricien, B2V ou à passer sous 90 j", "Permis B", "Ténue en hauteur"],
    benefits: ["B2V payé", "Véhicule", "Prime humidité 120 €"],
    skills: ["Électricité", "Onduleurs", "Habilitation", "Photovoltaïque"],
    collection: "terrain",
  }),
  job({
    companySlug: "loire-chaleur",
    slug: "plombier-chauffagiste-nantes",
    title: "Plombier-chauffagiste",
    team: "PAC Loire",
    city: "Nantes",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 30000,
    salaryMax: 36000,
    description: "PAC et chaudières Nantes / Saint-Nazaire. Astreinte 1/6 écrite. Un jour slasher possible le vendredi.",
    responsibilities: ["Entretien PAC", "Dépannage 4 h", "Devis honnêtes"],
    requirements: ["PGN ou 3 ans", "Permis B", "Fluides frigorigènes ou à passer"],
    benefits: ["Astreinte majorée", "Véhicule", "Outillage neuf"],
    skills: ["Plomberie", "PAC", "Chauffage", "Fluides"],
    collection: "terrain",
    pool: "slasher",
  }),
  job({
    companySlug: "flandre-soin",
    slug: "aide-soignant-lille",
    title: "Aide-soignant·e Ehpad / CHU",
    team: "Pôle Lille",
    city: "Lille",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 24000,
    salaryMax: 29000,
    description: "Lille-Roubaix. Try & Buy 5 jours payés. Garde d’enfants partenaire, chèque chaussures. Pas un pool jetable.",
    responsibilities: ["Toilette, transmissions", "Un secteur nommé", "Alerte encadrant"],
    requirements: ["DEAS ou 1 an", "Français de service"],
    benefits: ["Try & Buy payé", "Prime dimanche", "Garde partenaire"],
    skills: ["Soin", "DEAS", "Transmission", "Manutention"],
    collection: "sante",
    pool: "rsa",
  }),
  job({
    companySlug: "rhin-atome",
    slug: "technicien-nucleaire-strasbourg",
    title: "Technicien de maintenance nucléaire",
    team: "CNPE / Rhin",
    city: "Strasbourg",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 38000,
    salaryMax: 48000,
    description: "Habilitation, consignation, allemand de consigne un plus. Astreinte 1/6. Scarcity haut.",
    responsibilities: ["Arrêts de tranche", "Consignation", "Compte-rendu ASN lisible"],
    requirements: ["Maintenance industrielle 5 ans", "Habilitation ou à passer sur place", "Français d’atelier"],
    nice: ["Allemand", "CACES"],
    benefits: ["Habilitation interne", "Prime de site", "Cantine 19 h"],
    skills: ["Consignation", "Habilitation", "Nucléaire", "CACES"],
    collection: "terrain",
  }),
  job({
    companySlug: "garonne-toits",
    slug: "couvreur-bordeaux",
    title: "Couvreur / zingueur",
    team: "Toits 33",
    city: "Bordeaux",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 28000,
    salaryMax: 34000,
    description: "Ardoises, zinc, hauteur. Harnais neuf. Cédant à 61 ans : parcours salarié → repreneur ouvert.",
    responsibilities: ["Couverture", "Zinguerie", "Sécurité hauteur"],
    requirements: ["2 ans couverture", "Ténue hauteur", "Permis B"],
    benefits: ["Jours pluie payés", "Harnais", "Option reprise 18 mois"],
    skills: ["Couverture", "Zinc", "Hauteur", "BTP"],
    collection: "terrain",
    pool: "reprise",
  }),
  job({
    companySlug: "alpes-chantier",
    slug: "conducteur-travaux-grenoble",
    title: "Conducteur de travaux",
    team: "Collèges / ombrières",
    city: "Grenoble",
    country: "France",
    remoteType: "hybrid",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 42000,
    salaryMax: 52000,
    description: "4 à 6 chantiers Isère. Retard dit le jour même. Épreuve planning dans l’offre.",
    responsibilities: ["Planning", "Sous-traitance", "Réunions mairie"],
    requirements: ["5 ans Cdt", "Permis B", "Lecture de plans"],
    benefits: ["Véhicule", "Téléphone", "Pas d’astreinte"],
    skills: ["Chantier", "Planning", "BTP", "Marchés publics"],
    collection: "terrain",
  }),
  job({
    companySlug: "midi-soin",
    slug: "auxiliaire-montpellier",
    title: "Auxiliaire de vie à domicile",
    team: "Secteur 34",
    city: "Montpellier",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 25000,
    salaryMax: 29000,
    description: "Cinq personnes par jour. Trajets payés. Matrice RSA : mobilité + garde.",
    responsibilities: ["Tournée 5", "Transmissions", "Refus de soin nommé"],
    requirements: ["DEAES ou 2 ans", "Permis B"],
    benefits: ["Trajets", "13e mois", "Garde partenaire"],
    skills: ["Soin", "DEAES", "Présence"],
    collection: "sante",
    pool: "rsa",
  }),
  job({
    companySlug: "finistere-routes",
    slug: "conducteur-spl-brest",
    title: "Conducteur SPL / transport technique",
    team: "Lignes 29",
    city: "Brest",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 28000,
    salaryMax: 33000,
    description: "Planning figé 4 semaines. Pas de dimanche surprise. SPL, FIMO à jour.",
    responsibilities: ["Tournées techniques", "Fiches de charge", "Relais véhicule"],
    requirements: ["SPL", "FIMO", "Casier compatible"],
    benefits: ["Planning figé", "Heures sup", "Véhicule relais"],
    skills: ["SPL", "Transport", "FIMO"],
    collection: "terrain",
  }),
  job({
    companySlug: "releve",
    slug: "expertise-volante-releve",
    title: "Expert maintenance fractional (8–16 h)",
    team: "Atelier Fos",
    city: "Fos-sur-Mer",
    country: "France",
    remoteType: "hybrid",
    contract: "freelance",
    seniority: "senior",
    salaryMin: 52000,
    salaryMax: 72000,
    description: "Créneaux 8 à 16 h / semaine. Plusieurs sites Relève. Pas de 3×8. Tarif journalier publié, pénibilité aménagée.",
    responsibilities: ["Revue presses", "Tutorat chef d’équipe", "Astreinte non"],
    requirements: ["15 ans maintenance", "Consignation", "Fos ou Aix"],
    benefits: ["Jours figés", "Pas de nuit", "TJM 450–520 €"],
    skills: ["Maintenance", "Consignation", "Hydraulique"],
    collection: "terrain",
    pool: "senior-fractional",
    applicants: 3,
    views: 70,
  }),
  job({
    companySlug: "releve",
    slug: "binome-atelier-releve",
    title: "Binôme chef d’équipe + technicien",
    team: "Ligne 2",
    city: "Fos-sur-Mer",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "mid",
    salaryMin: 34000,
    salaryMax: 46000,
    description: "Deux contrats, une offre. Senior consignation + junior méthodes. On n’embauche pas l’un sans l’autre.",
    responsibilities: ["Tenir la ligne", "Former le geste", "Planning 4 semaines"],
    requirements: ["Un des deux profils : 8 ans atelier OU 2 ans méthodes", "Français de consigne"],
    benefits: ["Deux salaires publiés", "Tutorat payé", "Prime binôme"],
    skills: ["Maintenance", "Tutorat", "Méthodes"],
    collection: "terrain",
    pool: "binome",
  }),
  job({
    companySlug: "releve",
    slug: "repreneur-atelier-releve",
    title: "Salarié → repreneur d’atelier",
    team: "Direction Fos",
    city: "Fos-sur-Mer",
    country: "France",
    remoteType: "onsite",
    contract: "cdi",
    seniority: "senior",
    salaryMin: 48000,
    salaryMax: 62000,
    description: "Cédant 62 ans. 18 mois salarié, option, chiffre réel. Pas un LBO théâtre.",
    responsibilities: ["Tenir l’atelier", "Clients nommés", "Reprise tutorée"],
    requirements: ["Maintenance 10 ans", "Apport ou accompagnement (écrit)", "Fos"],
    benefits: ["Option 18 mois", "Accompagnement expert-comptable", "Salaire pendant la transition"],
    skills: ["Maintenance", "Gestion", "Reprise"],
    collection: "terrain",
    pool: "reprise",
  }),
];
