/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademiesRouteImport } from './routes/academies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApprendreRouteImport } from './routes/apprendre'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as EuropeRouteImport } from './routes/europe'
import { Route as FeedDotjsonRouteImport } from './routes/feed[.]json'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LexiqueRouteImport } from './routes/lexique'
import { Route as LieuxRouteImport } from './routes/lieux'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarcheRouteImport } from './routes/marche'
import { Route as MarchesRouteImport } from './routes/marches'
import { Route as MeRouteImport } from './routes/me'
import { Route as MetiersRouteImport } from './routes/metiers'
import { Route as PacteRouteImport } from './routes/pacte'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PostRouteImport } from './routes/post'
import { Route as PpqcRouteImport } from './routes/ppqc'
import { Route as PreuveRouteImport } from './routes/preuve'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SavoirsRouteImport } from './routes/savoirs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TensionRouteImport } from './routes/tension'
import { Route as ViviersRouteImport } from './routes/viviers'
import { Route as ApprendreIndexRouteImport } from './routes/apprendre.index'
import { Route as ApprendreSlugRouteImport } from './routes/apprendre.$slug'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as DriveIndexRouteImport } from './routes/drive.index'
import { Route as DriveIdRouteImport } from './routes/drive.$id'
import { Route as FeedSlugDotmdRouteImport } from './routes/feed.$slug[.]md'
import { Route as FichiersIdRouteImport } from './routes/fichiers.$id'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as LieuxIndexRouteImport } from './routes/lieux.index'
import { Route as LieuxCityRouteImport } from './routes/lieux.$city'
import { Route as LieuxDepartementsRouteImport } from './routes/lieux.departements'
import { Route as LieuxRegionsRouteImport } from './routes/lieux.regions'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as MeAcademieRouteImport } from './routes/me.academie'
import { Route as MeBriefRouteImport } from './routes/me.brief'
import { Route as MeCarnetRouteImport } from './routes/me.carnet'
import { Route as MeCckRouteImport } from './routes/me.cck'
import { Route as MeCreneauxRouteImport } from './routes/me.creneaux'
import { Route as MeDriveRouteImport } from './routes/me.drive'
import { Route as MeEpreuveRouteImport } from './routes/me.epreuve'
import { Route as MeFormationRouteImport } from './routes/me.formation'
import { Route as MeMaisonRouteImport } from './routes/me.maison'
import { Route as MeTrackerRouteImport } from './routes/me.tracker'
import { Route as MetiersIndexRouteImport } from './routes/metiers.index'
import { Route as MetiersSlugRouteImport } from './routes/metiers.$slug'
import { Route as SavoirsIndexRouteImport } from './routes/savoirs.index'
import { Route as SavoirsCatRouteImport } from './routes/savoirs.$cat'
import { Route as TalentsSlugRouteImport } from './routes/talents.$slug'
import { Route as ViviersIndexRouteImport } from './routes/viviers.index'
import { Route as ViviersSlugRouteImport } from './routes/viviers.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CompaniesSlugIndexRouteImport } from './routes/companies.$slug.index'
import { Route as CompaniesSlugEquipesRouteImport } from './routes/companies.$slug.equipes'
import { Route as CompaniesSlugJournalRouteImport } from './routes/companies.$slug.journal'
import { Route as CompaniesSlugMediasRouteImport } from './routes/companies.$slug.medias'
import { Route as CompaniesSlugOffresRouteImport } from './routes/companies.$slug.offres'
import { Route as CompaniesSlugPreuvesRouteImport } from './routes/companies.$slug.preuves'
import { Route as CompaniesSlugRdvRouteImport } from './routes/companies.$slug.rdv'
import { Route as CompaniesSlugAcademieRouteImport } from './routes/companies.$slug_.academie'
import { Route as DriveMediaIdRouteImport } from './routes/drive.media.$id'
import { Route as FeedMaisonsSlugDotmdRouteImport } from './routes/feed.maisons.$slug[.]md'
import { Route as LieuxDepartementsIndexRouteImport } from './routes/lieux.departements.index'
import { Route as LieuxDepartementsSlugRouteImport } from './routes/lieux.departements.$slug'
import { Route as LieuxRegionsIndexRouteImport } from './routes/lieux.regions.index'
import { Route as LieuxRegionsSlugRouteImport } from './routes/lieux.regions.$slug'
import { Route as SavoirsCatIndexRouteImport } from './routes/savoirs.$cat.index'
import { Route as SavoirsCatSlugRouteImport } from './routes/savoirs.$cat.$slug'
import { Route as CompaniesSlugAcademieIndexRouteImport } from './routes/companies.$slug_.academie.index'
import { Route as CompaniesSlugAcademieCourseRouteImport } from './routes/companies.$slug_.academie.$course'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesRoute = AcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprendreRoute = ApprendreRouteImport.update({
  id: '/apprendre',
  path: '/apprendre',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const EuropeRoute = EuropeRouteImport.update({
  id: '/europe',
  path: '/europe',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotjsonRoute = FeedDotjsonRouteImport.update({
  id: '/feed.json',
  path: '/feed.json',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiqueRoute = LexiqueRouteImport.update({
  id: '/lexique',
  path: '/lexique',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuxRoute = LieuxRouteImport.update({
  id: '/lieux',
  path: '/lieux',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcheRoute = MarcheRouteImport.update({
  id: '/marche',
  path: '/marche',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesRoute = MarchesRouteImport.update({
  id: '/marches',
  path: '/marches',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MetiersRoute = MetiersRouteImport.update({
  id: '/metiers',
  path: '/metiers',
  getParentRoute: () => rootRouteImport,
} as any)
const PacteRoute = PacteRouteImport.update({
  id: '/pacte',
  path: '/pacte',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PpqcRoute = PpqcRouteImport.update({
  id: '/ppqc',
  path: '/ppqc',
  getParentRoute: () => rootRouteImport,
} as any)
const PreuveRoute = PreuveRouteImport.update({
  id: '/preuve',
  path: '/preuve',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SavoirsRoute = SavoirsRouteImport.update({
  id: '/savoirs',
  path: '/savoirs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TensionRoute = TensionRouteImport.update({
  id: '/tension',
  path: '/tension',
  getParentRoute: () => rootRouteImport,
} as any)
const ViviersRoute = ViviersRouteImport.update({
  id: '/viviers',
  path: '/viviers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprendreIndexRoute = ApprendreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApprendreRoute,
} as any)
const ApprendreSlugRoute = ApprendreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApprendreRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompaniesRoute,
} as any)
const DriveIndexRoute = DriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriveRoute,
} as any)
const DriveIdRoute = DriveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DriveRoute,
} as any)
const FeedSlugDotmdRoute = FeedSlugDotmdRouteImport.update({
  id: '/feed/$slug.md',
  path: '/feed/$slug.md',
  getParentRoute: () => rootRouteImport,
} as any)
const FichiersIdRoute = FichiersIdRouteImport.update({
  id: '/fichiers/$id',
  path: '/fichiers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const LieuxIndexRoute = LieuxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LieuxRoute,
} as any)
const LieuxCityRoute = LieuxCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => LieuxRoute,
} as any)
const LieuxDepartementsRoute = LieuxDepartementsRouteImport.update({
  id: '/departements',
  path: '/departements',
  getParentRoute: () => LieuxRoute,
} as any)
const LieuxRegionsRoute = LieuxRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => LieuxRoute,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const MeAcademieRoute = MeAcademieRouteImport.update({
  id: '/academie',
  path: '/academie',
  getParentRoute: () => MeRoute,
} as any)
const MeBriefRoute = MeBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => MeRoute,
} as any)
const MeCarnetRoute = MeCarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => MeRoute,
} as any)
const MeCckRoute = MeCckRouteImport.update({
  id: '/cck',
  path: '/cck',
  getParentRoute: () => MeRoute,
} as any)
const MeCreneauxRoute = MeCreneauxRouteImport.update({
  id: '/creneaux',
  path: '/creneaux',
  getParentRoute: () => MeRoute,
} as any)
const MeDriveRoute = MeDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => MeRoute,
} as any)
const MeEpreuveRoute = MeEpreuveRouteImport.update({
  id: '/epreuve',
  path: '/epreuve',
  getParentRoute: () => MeRoute,
} as any)
const MeFormationRoute = MeFormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => MeRoute,
} as any)
const MeMaisonRoute = MeMaisonRouteImport.update({
  id: '/maison',
  path: '/maison',
  getParentRoute: () => MeRoute,
} as any)
const MeTrackerRoute = MeTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => MeRoute,
} as any)
const MetiersIndexRoute = MetiersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetiersRoute,
} as any)
const MetiersSlugRoute = MetiersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MetiersRoute,
} as any)
const SavoirsIndexRoute = SavoirsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SavoirsRoute,
} as any)
const SavoirsCatRoute = SavoirsCatRouteImport.update({
  id: '/$cat',
  path: '/$cat',
  getParentRoute: () => SavoirsRoute,
} as any)
const TalentsSlugRoute = TalentsSlugRouteImport.update({
  id: '/talents/$slug',
  path: '/talents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ViviersIndexRoute = ViviersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViviersRoute,
} as any)
const ViviersSlugRoute = ViviersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ViviersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugIndexRoute = CompaniesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesSlugRoute,
} as any)
const CompaniesSlugEquipesRoute = CompaniesSlugEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => CompaniesSlugRoute,
} as any)
const CompaniesSlugJournalRoute = CompaniesSlugJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => CompaniesSlugRoute,
} as any)
const CompaniesSlugMediasRoute = CompaniesSlugMediasRouteImport.update({
  id: '/medias',
  path: '/medias',
  getParentRoute: () => CompaniesSlugRoute,
} as any)
const CompaniesSlugOffresRoute = CompaniesSlugOffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => CompaniesSlugRoute,
} as any)
const CompaniesSlugPreuvesRoute = CompaniesSlugPreuvesRouteImport.update({
  id: '/preuves',
  path: '/preuves',
  getParentRoute: () => CompaniesSlugRoute,
} as any)
const CompaniesSlugRdvRoute = CompaniesSlugRdvRouteImport.update({
  id: '/rdv',
  path: '/rdv',
  getParentRoute: () => CompaniesSlugRoute,
} as any)
const CompaniesSlugAcademieRoute = CompaniesSlugAcademieRouteImport.update({
  id: '/$slug_/academie',
  path: '/$slug/academie',
  getParentRoute: () => CompaniesRoute,
} as any)
const DriveMediaIdRoute = DriveMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => DriveRoute,
} as any)
const FeedMaisonsSlugDotmdRoute = FeedMaisonsSlugDotmdRouteImport.update({
  id: '/feed/maisons/$slug.md',
  path: '/feed/maisons/$slug.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuxDepartementsIndexRoute = LieuxDepartementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LieuxDepartementsRoute,
} as any)
const LieuxDepartementsSlugRoute = LieuxDepartementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LieuxDepartementsRoute,
} as any)
const LieuxRegionsIndexRoute = LieuxRegionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LieuxRegionsRoute,
} as any)
const LieuxRegionsSlugRoute = LieuxRegionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LieuxRegionsRoute,
} as any)
const SavoirsCatIndexRoute = SavoirsCatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SavoirsCatRoute,
} as any)
const SavoirsCatSlugRoute = SavoirsCatSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SavoirsCatRoute,
} as any)
const CompaniesSlugAcademieIndexRoute =
  CompaniesSlugAcademieIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompaniesSlugAcademieRoute,
  } as any)
const CompaniesSlugAcademieCourseRoute =
  CompaniesSlugAcademieCourseRouteImport.update({
    id: '/$course',
    path: '/$course',
    getParentRoute: () => CompaniesSlugAcademieRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academies': typeof AcademiesRoute
  '/admin': typeof AdminRoute
  '/apprendre': typeof ApprendreRouteWithChildren
  '/coach': typeof CoachRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/drive': typeof DriveRouteWithChildren
  '/europe': typeof EuropeRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/guides': typeof GuidesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/lexique': typeof LexiqueRoute
  '/lieux': typeof LieuxRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/marche': typeof MarcheRoute
  '/marches': typeof MarchesRoute
  '/me': typeof MeRouteWithChildren
  '/metiers': typeof MetiersRouteWithChildren
  '/pacte': typeof PacteRoute
  '/passport': typeof PassportRoute
  '/post': typeof PostRoute
  '/ppqc': typeof PpqcRoute
  '/preuve': typeof PreuveRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/savoirs': typeof SavoirsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tension': typeof TensionRoute
  '/viviers': typeof ViviersRouteWithChildren
  '/apprendre/$slug': typeof ApprendreSlugRoute
  '/companies/$slug': typeof CompaniesSlugRouteWithChildren
  '/drive/$id': typeof DriveIdRoute
  '/feed/$slug.md': typeof FeedSlugDotmdRoute
  '/fichiers/$id': typeof FichiersIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/lieux/$city': typeof LieuxCityRoute
  '/lieux/departements': typeof LieuxDepartementsRouteWithChildren
  '/lieux/regions': typeof LieuxRegionsRouteWithChildren
  '/me/academie': typeof MeAcademieRoute
  '/me/brief': typeof MeBriefRoute
  '/me/carnet': typeof MeCarnetRoute
  '/me/cck': typeof MeCckRoute
  '/me/creneaux': typeof MeCreneauxRoute
  '/me/drive': typeof MeDriveRoute
  '/me/epreuve': typeof MeEpreuveRoute
  '/me/formation': typeof MeFormationRoute
  '/me/maison': typeof MeMaisonRoute
  '/me/tracker': typeof MeTrackerRoute
  '/metiers/$slug': typeof MetiersSlugRoute
  '/savoirs/$cat': typeof SavoirsCatRouteWithChildren
  '/talents/$slug': typeof TalentsSlugRoute
  '/viviers/$slug': typeof ViviersSlugRoute
  '/apprendre/': typeof ApprendreIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/drive/': typeof DriveIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/lieux/': typeof LieuxIndexRoute
  '/me/': typeof MeIndexRoute
  '/metiers/': typeof MetiersIndexRoute
  '/savoirs/': typeof SavoirsIndexRoute
  '/viviers/': typeof ViviersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/companies/$slug/equipes': typeof CompaniesSlugEquipesRoute
  '/companies/$slug/journal': typeof CompaniesSlugJournalRoute
  '/companies/$slug/medias': typeof CompaniesSlugMediasRoute
  '/companies/$slug/offres': typeof CompaniesSlugOffresRoute
  '/companies/$slug/preuves': typeof CompaniesSlugPreuvesRoute
  '/companies/$slug/rdv': typeof CompaniesSlugRdvRoute
  '/companies/$slug/academie': typeof CompaniesSlugAcademieRouteWithChildren
  '/drive/media/$id': typeof DriveMediaIdRoute
  '/feed/maisons/$slug.md': typeof FeedMaisonsSlugDotmdRoute
  '/lieux/departements/$slug': typeof LieuxDepartementsSlugRoute
  '/lieux/regions/$slug': typeof LieuxRegionsSlugRoute
  '/savoirs/$cat/$slug': typeof SavoirsCatSlugRoute
  '/companies/$slug/': typeof CompaniesSlugIndexRoute
  '/lieux/departements/': typeof LieuxDepartementsIndexRoute
  '/lieux/regions/': typeof LieuxRegionsIndexRoute
  '/savoirs/$cat/': typeof SavoirsCatIndexRoute
  '/companies/$slug/academie/$course': typeof CompaniesSlugAcademieCourseRoute
  '/companies/$slug/academie/': typeof CompaniesSlugAcademieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academies': typeof AcademiesRoute
  '/admin': typeof AdminRoute
  '/coach': typeof CoachRoute
  '/europe': typeof EuropeRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/lexique': typeof LexiqueRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/marche': typeof MarcheRoute
  '/marches': typeof MarchesRoute
  '/pacte': typeof PacteRoute
  '/passport': typeof PassportRoute
  '/post': typeof PostRoute
  '/ppqc': typeof PpqcRoute
  '/preuve': typeof PreuveRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tension': typeof TensionRoute
  '/apprendre/$slug': typeof ApprendreSlugRoute
  '/drive/$id': typeof DriveIdRoute
  '/feed/$slug.md': typeof FeedSlugDotmdRoute
  '/fichiers/$id': typeof FichiersIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/lieux/$city': typeof LieuxCityRoute
  '/me/academie': typeof MeAcademieRoute
  '/me/brief': typeof MeBriefRoute
  '/me/carnet': typeof MeCarnetRoute
  '/me/cck': typeof MeCckRoute
  '/me/creneaux': typeof MeCreneauxRoute
  '/me/drive': typeof MeDriveRoute
  '/me/epreuve': typeof MeEpreuveRoute
  '/me/formation': typeof MeFormationRoute
  '/me/maison': typeof MeMaisonRoute
  '/me/tracker': typeof MeTrackerRoute
  '/metiers/$slug': typeof MetiersSlugRoute
  '/talents/$slug': typeof TalentsSlugRoute
  '/viviers/$slug': typeof ViviersSlugRoute
  '/apprendre': typeof ApprendreIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/drive': typeof DriveIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/lieux': typeof LieuxIndexRoute
  '/me': typeof MeIndexRoute
  '/metiers': typeof MetiersIndexRoute
  '/savoirs': typeof SavoirsIndexRoute
  '/viviers': typeof ViviersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/companies/$slug/equipes': typeof CompaniesSlugEquipesRoute
  '/companies/$slug/journal': typeof CompaniesSlugJournalRoute
  '/companies/$slug/medias': typeof CompaniesSlugMediasRoute
  '/companies/$slug/offres': typeof CompaniesSlugOffresRoute
  '/companies/$slug/preuves': typeof CompaniesSlugPreuvesRoute
  '/companies/$slug/rdv': typeof CompaniesSlugRdvRoute
  '/drive/media/$id': typeof DriveMediaIdRoute
  '/feed/maisons/$slug.md': typeof FeedMaisonsSlugDotmdRoute
  '/lieux/departements/$slug': typeof LieuxDepartementsSlugRoute
  '/lieux/regions/$slug': typeof LieuxRegionsSlugRoute
  '/savoirs/$cat/$slug': typeof SavoirsCatSlugRoute
  '/companies/$slug': typeof CompaniesSlugIndexRoute
  '/lieux/departements': typeof LieuxDepartementsIndexRoute
  '/lieux/regions': typeof LieuxRegionsIndexRoute
  '/savoirs/$cat': typeof SavoirsCatIndexRoute
  '/companies/$slug/academie/$course': typeof CompaniesSlugAcademieCourseRoute
  '/companies/$slug/academie': typeof CompaniesSlugAcademieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academies': typeof AcademiesRoute
  '/admin': typeof AdminRoute
  '/apprendre': typeof ApprendreRouteWithChildren
  '/coach': typeof CoachRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/drive': typeof DriveRouteWithChildren
  '/europe': typeof EuropeRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/guides': typeof GuidesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/lexique': typeof LexiqueRoute
  '/lieux': typeof LieuxRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/marche': typeof MarcheRoute
  '/marches': typeof MarchesRoute
  '/me': typeof MeRouteWithChildren
  '/metiers': typeof MetiersRouteWithChildren
  '/pacte': typeof PacteRoute
  '/passport': typeof PassportRoute
  '/post': typeof PostRoute
  '/ppqc': typeof PpqcRoute
  '/preuve': typeof PreuveRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/savoirs': typeof SavoirsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tension': typeof TensionRoute
  '/viviers': typeof ViviersRouteWithChildren
  '/apprendre/$slug': typeof ApprendreSlugRoute
  '/companies/$slug': typeof CompaniesSlugRouteWithChildren
  '/drive/$id': typeof DriveIdRoute
  '/feed/$slug.md': typeof FeedSlugDotmdRoute
  '/fichiers/$id': typeof FichiersIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/lieux/$city': typeof LieuxCityRoute
  '/lieux/departements': typeof LieuxDepartementsRouteWithChildren
  '/lieux/regions': typeof LieuxRegionsRouteWithChildren
  '/me/academie': typeof MeAcademieRoute
  '/me/brief': typeof MeBriefRoute
  '/me/carnet': typeof MeCarnetRoute
  '/me/cck': typeof MeCckRoute
  '/me/creneaux': typeof MeCreneauxRoute
  '/me/drive': typeof MeDriveRoute
  '/me/epreuve': typeof MeEpreuveRoute
  '/me/formation': typeof MeFormationRoute
  '/me/maison': typeof MeMaisonRoute
  '/me/tracker': typeof MeTrackerRoute
  '/metiers/$slug': typeof MetiersSlugRoute
  '/savoirs/$cat': typeof SavoirsCatRouteWithChildren
  '/talents/$slug': typeof TalentsSlugRoute
  '/viviers/$slug': typeof ViviersSlugRoute
  '/apprendre/': typeof ApprendreIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/drive/': typeof DriveIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/lieux/': typeof LieuxIndexRoute
  '/me/': typeof MeIndexRoute
  '/metiers/': typeof MetiersIndexRoute
  '/savoirs/': typeof SavoirsIndexRoute
  '/viviers/': typeof ViviersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/companies/$slug/equipes': typeof CompaniesSlugEquipesRoute
  '/companies/$slug/journal': typeof CompaniesSlugJournalRoute
  '/companies/$slug/medias': typeof CompaniesSlugMediasRoute
  '/companies/$slug/offres': typeof CompaniesSlugOffresRoute
  '/companies/$slug/preuves': typeof CompaniesSlugPreuvesRoute
  '/companies/$slug/rdv': typeof CompaniesSlugRdvRoute
  '/companies/$slug_/academie': typeof CompaniesSlugAcademieRouteWithChildren
  '/drive/media/$id': typeof DriveMediaIdRoute
  '/feed/maisons/$slug.md': typeof FeedMaisonsSlugDotmdRoute
  '/lieux/departements/$slug': typeof LieuxDepartementsSlugRoute
  '/lieux/regions/$slug': typeof LieuxRegionsSlugRoute
  '/savoirs/$cat/$slug': typeof SavoirsCatSlugRoute
  '/companies/$slug/': typeof CompaniesSlugIndexRoute
  '/lieux/departements/': typeof LieuxDepartementsIndexRoute
  '/lieux/regions/': typeof LieuxRegionsIndexRoute
  '/savoirs/$cat/': typeof SavoirsCatIndexRoute
  '/companies/$slug_/academie/$course': typeof CompaniesSlugAcademieCourseRoute
  '/companies/$slug_/academie/': typeof CompaniesSlugAcademieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academies'
    | '/admin'
    | '/apprendre'
    | '/coach'
    | '/companies'
    | '/drive'
    | '/europe'
    | '/feed.json'
    | '/guides'
    | '/jobs'
    | '/journal'
    | '/lexique'
    | '/lieux'
    | '/llms.txt'
    | '/login'
    | '/marche'
    | '/marches'
    | '/me'
    | '/metiers'
    | '/pacte'
    | '/passport'
    | '/post'
    | '/ppqc'
    | '/preuve'
    | '/robots.txt'
    | '/savoirs'
    | '/sitemap.xml'
    | '/tension'
    | '/viviers'
    | '/apprendre/$slug'
    | '/companies/$slug'
    | '/drive/$id'
    | '/feed/$slug.md'
    | '/fichiers/$id'
    | '/guides/$slug'
    | '/jobs/$slug'
    | '/journal/$slug'
    | '/lieux/$city'
    | '/lieux/departements'
    | '/lieux/regions'
    | '/me/academie'
    | '/me/brief'
    | '/me/carnet'
    | '/me/cck'
    | '/me/creneaux'
    | '/me/drive'
    | '/me/epreuve'
    | '/me/formation'
    | '/me/maison'
    | '/me/tracker'
    | '/metiers/$slug'
    | '/savoirs/$cat'
    | '/talents/$slug'
    | '/viviers/$slug'
    | '/apprendre/'
    | '/companies/'
    | '/drive/'
    | '/guides/'
    | '/jobs/'
    | '/journal/'
    | '/lieux/'
    | '/me/'
    | '/metiers/'
    | '/savoirs/'
    | '/viviers/'
    | '/api/auth/$'
    | '/companies/$slug/equipes'
    | '/companies/$slug/journal'
    | '/companies/$slug/medias'
    | '/companies/$slug/offres'
    | '/companies/$slug/preuves'
    | '/companies/$slug/rdv'
    | '/companies/$slug/academie'
    | '/drive/media/$id'
    | '/feed/maisons/$slug.md'
    | '/lieux/departements/$slug'
    | '/lieux/regions/$slug'
    | '/savoirs/$cat/$slug'
    | '/companies/$slug/'
    | '/lieux/departements/'
    | '/lieux/regions/'
    | '/savoirs/$cat/'
    | '/companies/$slug/academie/$course'
    | '/companies/$slug/academie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academies'
    | '/admin'
    | '/coach'
    | '/europe'
    | '/feed.json'
    | '/lexique'
    | '/llms.txt'
    | '/login'
    | '/marche'
    | '/marches'
    | '/pacte'
    | '/passport'
    | '/post'
    | '/ppqc'
    | '/preuve'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tension'
    | '/apprendre/$slug'
    | '/drive/$id'
    | '/feed/$slug.md'
    | '/fichiers/$id'
    | '/guides/$slug'
    | '/jobs/$slug'
    | '/journal/$slug'
    | '/lieux/$city'
    | '/me/academie'
    | '/me/brief'
    | '/me/carnet'
    | '/me/cck'
    | '/me/creneaux'
    | '/me/drive'
    | '/me/epreuve'
    | '/me/formation'
    | '/me/maison'
    | '/me/tracker'
    | '/metiers/$slug'
    | '/talents/$slug'
    | '/viviers/$slug'
    | '/apprendre'
    | '/companies'
    | '/drive'
    | '/guides'
    | '/jobs'
    | '/journal'
    | '/lieux'
    | '/me'
    | '/metiers'
    | '/savoirs'
    | '/viviers'
    | '/api/auth/$'
    | '/companies/$slug/equipes'
    | '/companies/$slug/journal'
    | '/companies/$slug/medias'
    | '/companies/$slug/offres'
    | '/companies/$slug/preuves'
    | '/companies/$slug/rdv'
    | '/drive/media/$id'
    | '/feed/maisons/$slug.md'
    | '/lieux/departements/$slug'
    | '/lieux/regions/$slug'
    | '/savoirs/$cat/$slug'
    | '/companies/$slug'
    | '/lieux/departements'
    | '/lieux/regions'
    | '/savoirs/$cat'
    | '/companies/$slug/academie/$course'
    | '/companies/$slug/academie'
  id:
    | '__root__'
    | '/'
    | '/academies'
    | '/admin'
    | '/apprendre'
    | '/coach'
    | '/companies'
    | '/drive'
    | '/europe'
    | '/feed.json'
    | '/guides'
    | '/jobs'
    | '/journal'
    | '/lexique'
    | '/lieux'
    | '/llms.txt'
    | '/login'
    | '/marche'
    | '/marches'
    | '/me'
    | '/metiers'
    | '/pacte'
    | '/passport'
    | '/post'
    | '/ppqc'
    | '/preuve'
    | '/robots.txt'
    | '/savoirs'
    | '/sitemap.xml'
    | '/tension'
    | '/viviers'
    | '/apprendre/$slug'
    | '/companies/$slug'
    | '/drive/$id'
    | '/feed/$slug.md'
    | '/fichiers/$id'
    | '/guides/$slug'
    | '/jobs/$slug'
    | '/journal/$slug'
    | '/lieux/$city'
    | '/lieux/departements'
    | '/lieux/regions'
    | '/me/academie'
    | '/me/brief'
    | '/me/carnet'
    | '/me/cck'
    | '/me/creneaux'
    | '/me/drive'
    | '/me/epreuve'
    | '/me/formation'
    | '/me/maison'
    | '/me/tracker'
    | '/metiers/$slug'
    | '/savoirs/$cat'
    | '/talents/$slug'
    | '/viviers/$slug'
    | '/apprendre/'
    | '/companies/'
    | '/drive/'
    | '/guides/'
    | '/jobs/'
    | '/journal/'
    | '/lieux/'
    | '/me/'
    | '/metiers/'
    | '/savoirs/'
    | '/viviers/'
    | '/api/auth/$'
    | '/companies/$slug/equipes'
    | '/companies/$slug/journal'
    | '/companies/$slug/medias'
    | '/companies/$slug/offres'
    | '/companies/$slug/preuves'
    | '/companies/$slug/rdv'
    | '/companies/$slug_/academie'
    | '/drive/media/$id'
    | '/feed/maisons/$slug.md'
    | '/lieux/departements/$slug'
    | '/lieux/regions/$slug'
    | '/savoirs/$cat/$slug'
    | '/companies/$slug/'
    | '/lieux/departements/'
    | '/lieux/regions/'
    | '/savoirs/$cat/'
    | '/companies/$slug_/academie/$course'
    | '/companies/$slug_/academie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiesRoute: typeof AcademiesRoute
  AdminRoute: typeof AdminRoute
  ApprendreRoute: typeof ApprendreRouteWithChildren
  CoachRoute: typeof CoachRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DriveRoute: typeof DriveRouteWithChildren
  EuropeRoute: typeof EuropeRoute
  FeedDotjsonRoute: typeof FeedDotjsonRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  LexiqueRoute: typeof LexiqueRoute
  LieuxRoute: typeof LieuxRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  MarcheRoute: typeof MarcheRoute
  MarchesRoute: typeof MarchesRoute
  MeRoute: typeof MeRouteWithChildren
  MetiersRoute: typeof MetiersRouteWithChildren
  PacteRoute: typeof PacteRoute
  PassportRoute: typeof PassportRoute
  PostRoute: typeof PostRoute
  PpqcRoute: typeof PpqcRoute
  PreuveRoute: typeof PreuveRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SavoirsRoute: typeof SavoirsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TensionRoute: typeof TensionRoute
  ViviersRoute: typeof ViviersRouteWithChildren
  FeedSlugDotmdRoute: typeof FeedSlugDotmdRoute
  FichiersIdRoute: typeof FichiersIdRoute
  TalentsSlugRoute: typeof TalentsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  FeedMaisonsSlugDotmdRoute: typeof FeedMaisonsSlugDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies': {
      id: '/academies'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AcademiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apprendre': {
      id: '/apprendre'
      path: '/apprendre'
      fullPath: '/apprendre'
      preLoaderRoute: typeof ApprendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/europe': {
      id: '/europe'
      path: '/europe'
      fullPath: '/europe'
      preLoaderRoute: typeof EuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.json': {
      id: '/feed.json'
      path: '/feed.json'
      fullPath: '/feed.json'
      preLoaderRoute: typeof FeedDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexique': {
      id: '/lexique'
      path: '/lexique'
      fullPath: '/lexique'
      preLoaderRoute: typeof LexiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieux': {
      id: '/lieux'
      path: '/lieux'
      fullPath: '/lieux'
      preLoaderRoute: typeof LieuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marche': {
      id: '/marche'
      path: '/marche'
      fullPath: '/marche'
      preLoaderRoute: typeof MarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches': {
      id: '/marches'
      path: '/marches'
      fullPath: '/marches'
      preLoaderRoute: typeof MarchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metiers': {
      id: '/metiers'
      path: '/metiers'
      fullPath: '/metiers'
      preLoaderRoute: typeof MetiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacte': {
      id: '/pacte'
      path: '/pacte'
      fullPath: '/pacte'
      preLoaderRoute: typeof PacteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppqc': {
      id: '/ppqc'
      path: '/ppqc'
      fullPath: '/ppqc'
      preLoaderRoute: typeof PpqcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preuve': {
      id: '/preuve'
      path: '/preuve'
      fullPath: '/preuve'
      preLoaderRoute: typeof PreuveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savoirs': {
      id: '/savoirs'
      path: '/savoirs'
      fullPath: '/savoirs'
      preLoaderRoute: typeof SavoirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tension': {
      id: '/tension'
      path: '/tension'
      fullPath: '/tension'
      preLoaderRoute: typeof TensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viviers': {
      id: '/viviers'
      path: '/viviers'
      fullPath: '/viviers'
      preLoaderRoute: typeof ViviersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apprendre/': {
      id: '/apprendre/'
      path: '/'
      fullPath: '/apprendre/'
      preLoaderRoute: typeof ApprendreIndexRouteImport
      parentRoute: typeof ApprendreRoute
    }
    '/apprendre/$slug': {
      id: '/apprendre/$slug'
      path: '/$slug'
      fullPath: '/apprendre/$slug'
      preLoaderRoute: typeof ApprendreSlugRouteImport
      parentRoute: typeof ApprendreRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/drive/': {
      id: '/drive/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof DriveIndexRouteImport
      parentRoute: typeof DriveRoute
    }
    '/drive/$id': {
      id: '/drive/$id'
      path: '/$id'
      fullPath: '/drive/$id'
      preLoaderRoute: typeof DriveIdRouteImport
      parentRoute: typeof DriveRoute
    }
    '/feed/$slug.md': {
      id: '/feed/$slug.md'
      path: '/feed/$slug.md'
      fullPath: '/feed/$slug.md'
      preLoaderRoute: typeof FeedSlugDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichiers/$id': {
      id: '/fichiers/$id'
      path: '/fichiers/$id'
      fullPath: '/fichiers/$id'
      preLoaderRoute: typeof FichiersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/lieux/': {
      id: '/lieux/'
      path: '/'
      fullPath: '/lieux/'
      preLoaderRoute: typeof LieuxIndexRouteImport
      parentRoute: typeof LieuxRoute
    }
    '/lieux/$city': {
      id: '/lieux/$city'
      path: '/$city'
      fullPath: '/lieux/$city'
      preLoaderRoute: typeof LieuxCityRouteImport
      parentRoute: typeof LieuxRoute
    }
    '/lieux/departements': {
      id: '/lieux/departements'
      path: '/departements'
      fullPath: '/lieux/departements'
      preLoaderRoute: typeof LieuxDepartementsRouteImport
      parentRoute: typeof LieuxRoute
    }
    '/lieux/regions': {
      id: '/lieux/regions'
      path: '/regions'
      fullPath: '/lieux/regions'
      preLoaderRoute: typeof LieuxRegionsRouteImport
      parentRoute: typeof LieuxRoute
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/academie': {
      id: '/me/academie'
      path: '/academie'
      fullPath: '/me/academie'
      preLoaderRoute: typeof MeAcademieRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/brief': {
      id: '/me/brief'
      path: '/brief'
      fullPath: '/me/brief'
      preLoaderRoute: typeof MeBriefRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/carnet': {
      id: '/me/carnet'
      path: '/carnet'
      fullPath: '/me/carnet'
      preLoaderRoute: typeof MeCarnetRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/cck': {
      id: '/me/cck'
      path: '/cck'
      fullPath: '/me/cck'
      preLoaderRoute: typeof MeCckRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/creneaux': {
      id: '/me/creneaux'
      path: '/creneaux'
      fullPath: '/me/creneaux'
      preLoaderRoute: typeof MeCreneauxRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/drive': {
      id: '/me/drive'
      path: '/drive'
      fullPath: '/me/drive'
      preLoaderRoute: typeof MeDriveRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/epreuve': {
      id: '/me/epreuve'
      path: '/epreuve'
      fullPath: '/me/epreuve'
      preLoaderRoute: typeof MeEpreuveRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/formation': {
      id: '/me/formation'
      path: '/formation'
      fullPath: '/me/formation'
      preLoaderRoute: typeof MeFormationRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/maison': {
      id: '/me/maison'
      path: '/maison'
      fullPath: '/me/maison'
      preLoaderRoute: typeof MeMaisonRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/tracker': {
      id: '/me/tracker'
      path: '/tracker'
      fullPath: '/me/tracker'
      preLoaderRoute: typeof MeTrackerRouteImport
      parentRoute: typeof MeRoute
    }
    '/metiers/': {
      id: '/metiers/'
      path: '/'
      fullPath: '/metiers/'
      preLoaderRoute: typeof MetiersIndexRouteImport
      parentRoute: typeof MetiersRoute
    }
    '/metiers/$slug': {
      id: '/metiers/$slug'
      path: '/$slug'
      fullPath: '/metiers/$slug'
      preLoaderRoute: typeof MetiersSlugRouteImport
      parentRoute: typeof MetiersRoute
    }
    '/savoirs/': {
      id: '/savoirs/'
      path: '/'
      fullPath: '/savoirs/'
      preLoaderRoute: typeof SavoirsIndexRouteImport
      parentRoute: typeof SavoirsRoute
    }
    '/savoirs/$cat': {
      id: '/savoirs/$cat'
      path: '/$cat'
      fullPath: '/savoirs/$cat'
      preLoaderRoute: typeof SavoirsCatRouteImport
      parentRoute: typeof SavoirsRoute
    }
    '/talents/$slug': {
      id: '/talents/$slug'
      path: '/talents/$slug'
      fullPath: '/talents/$slug'
      preLoaderRoute: typeof TalentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viviers/': {
      id: '/viviers/'
      path: '/'
      fullPath: '/viviers/'
      preLoaderRoute: typeof ViviersIndexRouteImport
      parentRoute: typeof ViviersRoute
    }
    '/viviers/$slug': {
      id: '/viviers/$slug'
      path: '/$slug'
      fullPath: '/viviers/$slug'
      preLoaderRoute: typeof ViviersSlugRouteImport
      parentRoute: typeof ViviersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug/': {
      id: '/companies/$slug/'
      path: '/'
      fullPath: '/companies/$slug/'
      preLoaderRoute: typeof CompaniesSlugIndexRouteImport
      parentRoute: typeof CompaniesSlugRoute
    }
    '/companies/$slug/equipes': {
      id: '/companies/$slug/equipes'
      path: '/equipes'
      fullPath: '/companies/$slug/equipes'
      preLoaderRoute: typeof CompaniesSlugEquipesRouteImport
      parentRoute: typeof CompaniesSlugRoute
    }
    '/companies/$slug/journal': {
      id: '/companies/$slug/journal'
      path: '/journal'
      fullPath: '/companies/$slug/journal'
      preLoaderRoute: typeof CompaniesSlugJournalRouteImport
      parentRoute: typeof CompaniesSlugRoute
    }
    '/companies/$slug/medias': {
      id: '/companies/$slug/medias'
      path: '/medias'
      fullPath: '/companies/$slug/medias'
      preLoaderRoute: typeof CompaniesSlugMediasRouteImport
      parentRoute: typeof CompaniesSlugRoute
    }
    '/companies/$slug/offres': {
      id: '/companies/$slug/offres'
      path: '/offres'
      fullPath: '/companies/$slug/offres'
      preLoaderRoute: typeof CompaniesSlugOffresRouteImport
      parentRoute: typeof CompaniesSlugRoute
    }
    '/companies/$slug/preuves': {
      id: '/companies/$slug/preuves'
      path: '/preuves'
      fullPath: '/companies/$slug/preuves'
      preLoaderRoute: typeof CompaniesSlugPreuvesRouteImport
      parentRoute: typeof CompaniesSlugRoute
    }
    '/companies/$slug/rdv': {
      id: '/companies/$slug/rdv'
      path: '/rdv'
      fullPath: '/companies/$slug/rdv'
      preLoaderRoute: typeof CompaniesSlugRdvRouteImport
      parentRoute: typeof CompaniesSlugRoute
    }
    '/companies/$slug_/academie': {
      id: '/companies/$slug_/academie'
      path: '/$slug/academie'
      fullPath: '/companies/$slug/academie'
      preLoaderRoute: typeof CompaniesSlugAcademieRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/drive/media/$id': {
      id: '/drive/media/$id'
      path: '/media/$id'
      fullPath: '/drive/media/$id'
      preLoaderRoute: typeof DriveMediaIdRouteImport
      parentRoute: typeof DriveRoute
    }
    '/feed/maisons/$slug.md': {
      id: '/feed/maisons/$slug.md'
      path: '/feed/maisons/$slug.md'
      fullPath: '/feed/maisons/$slug.md'
      preLoaderRoute: typeof FeedMaisonsSlugDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieux/departements/': {
      id: '/lieux/departements/'
      path: '/'
      fullPath: '/lieux/departements/'
      preLoaderRoute: typeof LieuxDepartementsIndexRouteImport
      parentRoute: typeof LieuxDepartementsRoute
    }
    '/lieux/departements/$slug': {
      id: '/lieux/departements/$slug'
      path: '/$slug'
      fullPath: '/lieux/departements/$slug'
      preLoaderRoute: typeof LieuxDepartementsSlugRouteImport
      parentRoute: typeof LieuxDepartementsRoute
    }
    '/lieux/regions/': {
      id: '/lieux/regions/'
      path: '/'
      fullPath: '/lieux/regions/'
      preLoaderRoute: typeof LieuxRegionsIndexRouteImport
      parentRoute: typeof LieuxRegionsRoute
    }
    '/lieux/regions/$slug': {
      id: '/lieux/regions/$slug'
      path: '/$slug'
      fullPath: '/lieux/regions/$slug'
      preLoaderRoute: typeof LieuxRegionsSlugRouteImport
      parentRoute: typeof LieuxRegionsRoute
    }
    '/savoirs/$cat/': {
      id: '/savoirs/$cat/'
      path: '/'
      fullPath: '/savoirs/$cat/'
      preLoaderRoute: typeof SavoirsCatIndexRouteImport
      parentRoute: typeof SavoirsCatRoute
    }
    '/savoirs/$cat/$slug': {
      id: '/savoirs/$cat/$slug'
      path: '/$slug'
      fullPath: '/savoirs/$cat/$slug'
      preLoaderRoute: typeof SavoirsCatSlugRouteImport
      parentRoute: typeof SavoirsCatRoute
    }
    '/companies/$slug_/academie/': {
      id: '/companies/$slug_/academie/'
      path: '/'
      fullPath: '/companies/$slug/academie/'
      preLoaderRoute: typeof CompaniesSlugAcademieIndexRouteImport
      parentRoute: typeof CompaniesSlugAcademieRoute
    }
    '/companies/$slug_/academie/$course': {
      id: '/companies/$slug_/academie/$course'
      path: '/$course'
      fullPath: '/companies/$slug/academie/$course'
      preLoaderRoute: typeof CompaniesSlugAcademieCourseRouteImport
      parentRoute: typeof CompaniesSlugAcademieRoute
    }
  }
}

interface ApprendreRouteChildren {
  ApprendreSlugRoute: typeof ApprendreSlugRoute
  ApprendreIndexRoute: typeof ApprendreIndexRoute
}

const ApprendreRouteChildren: ApprendreRouteChildren = {
  ApprendreSlugRoute: ApprendreSlugRoute,
  ApprendreIndexRoute: ApprendreIndexRoute,
}

const ApprendreRouteWithChildren = ApprendreRoute._addFileChildren(
  ApprendreRouteChildren,
)

interface CompaniesSlugRouteChildren {
  CompaniesSlugEquipesRoute: typeof CompaniesSlugEquipesRoute
  CompaniesSlugJournalRoute: typeof CompaniesSlugJournalRoute
  CompaniesSlugMediasRoute: typeof CompaniesSlugMediasRoute
  CompaniesSlugOffresRoute: typeof CompaniesSlugOffresRoute
  CompaniesSlugPreuvesRoute: typeof CompaniesSlugPreuvesRoute
  CompaniesSlugRdvRoute: typeof CompaniesSlugRdvRoute
  CompaniesSlugIndexRoute: typeof CompaniesSlugIndexRoute
}

const CompaniesSlugRouteChildren: CompaniesSlugRouteChildren = {
  CompaniesSlugEquipesRoute: CompaniesSlugEquipesRoute,
  CompaniesSlugJournalRoute: CompaniesSlugJournalRoute,
  CompaniesSlugMediasRoute: CompaniesSlugMediasRoute,
  CompaniesSlugOffresRoute: CompaniesSlugOffresRoute,
  CompaniesSlugPreuvesRoute: CompaniesSlugPreuvesRoute,
  CompaniesSlugRdvRoute: CompaniesSlugRdvRoute,
  CompaniesSlugIndexRoute: CompaniesSlugIndexRoute,
}

const CompaniesSlugRouteWithChildren = CompaniesSlugRoute._addFileChildren(
  CompaniesSlugRouteChildren,
)

interface CompaniesSlugAcademieRouteChildren {
  CompaniesSlugAcademieCourseRoute: typeof CompaniesSlugAcademieCourseRoute
  CompaniesSlugAcademieIndexRoute: typeof CompaniesSlugAcademieIndexRoute
}

const CompaniesSlugAcademieRouteChildren: CompaniesSlugAcademieRouteChildren = {
  CompaniesSlugAcademieCourseRoute: CompaniesSlugAcademieCourseRoute,
  CompaniesSlugAcademieIndexRoute: CompaniesSlugAcademieIndexRoute,
}

const CompaniesSlugAcademieRouteWithChildren =
  CompaniesSlugAcademieRoute._addFileChildren(
    CompaniesSlugAcademieRouteChildren,
  )

interface CompaniesRouteChildren {
  CompaniesSlugRoute: typeof CompaniesSlugRouteWithChildren
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  CompaniesSlugAcademieRoute: typeof CompaniesSlugAcademieRouteWithChildren
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesSlugRoute: CompaniesSlugRouteWithChildren,
  CompaniesIndexRoute: CompaniesIndexRoute,
  CompaniesSlugAcademieRoute: CompaniesSlugAcademieRouteWithChildren,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface DriveRouteChildren {
  DriveIdRoute: typeof DriveIdRoute
  DriveIndexRoute: typeof DriveIndexRoute
  DriveMediaIdRoute: typeof DriveMediaIdRoute
}

const DriveRouteChildren: DriveRouteChildren = {
  DriveIdRoute: DriveIdRoute,
  DriveIndexRoute: DriveIndexRoute,
  DriveMediaIdRoute: DriveMediaIdRoute,
}

const DriveRouteWithChildren = DriveRoute._addFileChildren(DriveRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface JobsRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface LieuxDepartementsRouteChildren {
  LieuxDepartementsSlugRoute: typeof LieuxDepartementsSlugRoute
  LieuxDepartementsIndexRoute: typeof LieuxDepartementsIndexRoute
}

const LieuxDepartementsRouteChildren: LieuxDepartementsRouteChildren = {
  LieuxDepartementsSlugRoute: LieuxDepartementsSlugRoute,
  LieuxDepartementsIndexRoute: LieuxDepartementsIndexRoute,
}

const LieuxDepartementsRouteWithChildren =
  LieuxDepartementsRoute._addFileChildren(LieuxDepartementsRouteChildren)

interface LieuxRegionsRouteChildren {
  LieuxRegionsSlugRoute: typeof LieuxRegionsSlugRoute
  LieuxRegionsIndexRoute: typeof LieuxRegionsIndexRoute
}

const LieuxRegionsRouteChildren: LieuxRegionsRouteChildren = {
  LieuxRegionsSlugRoute: LieuxRegionsSlugRoute,
  LieuxRegionsIndexRoute: LieuxRegionsIndexRoute,
}

const LieuxRegionsRouteWithChildren = LieuxRegionsRoute._addFileChildren(
  LieuxRegionsRouteChildren,
)

interface LieuxRouteChildren {
  LieuxCityRoute: typeof LieuxCityRoute
  LieuxDepartementsRoute: typeof LieuxDepartementsRouteWithChildren
  LieuxRegionsRoute: typeof LieuxRegionsRouteWithChildren
  LieuxIndexRoute: typeof LieuxIndexRoute
}

const LieuxRouteChildren: LieuxRouteChildren = {
  LieuxCityRoute: LieuxCityRoute,
  LieuxDepartementsRoute: LieuxDepartementsRouteWithChildren,
  LieuxRegionsRoute: LieuxRegionsRouteWithChildren,
  LieuxIndexRoute: LieuxIndexRoute,
}

const LieuxRouteWithChildren = LieuxRoute._addFileChildren(LieuxRouteChildren)

interface MeRouteChildren {
  MeAcademieRoute: typeof MeAcademieRoute
  MeBriefRoute: typeof MeBriefRoute
  MeCarnetRoute: typeof MeCarnetRoute
  MeCckRoute: typeof MeCckRoute
  MeCreneauxRoute: typeof MeCreneauxRoute
  MeDriveRoute: typeof MeDriveRoute
  MeEpreuveRoute: typeof MeEpreuveRoute
  MeFormationRoute: typeof MeFormationRoute
  MeMaisonRoute: typeof MeMaisonRoute
  MeTrackerRoute: typeof MeTrackerRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeAcademieRoute: MeAcademieRoute,
  MeBriefRoute: MeBriefRoute,
  MeCarnetRoute: MeCarnetRoute,
  MeCckRoute: MeCckRoute,
  MeCreneauxRoute: MeCreneauxRoute,
  MeDriveRoute: MeDriveRoute,
  MeEpreuveRoute: MeEpreuveRoute,
  MeFormationRoute: MeFormationRoute,
  MeMaisonRoute: MeMaisonRoute,
  MeTrackerRoute: MeTrackerRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

interface MetiersRouteChildren {
  MetiersSlugRoute: typeof MetiersSlugRoute
  MetiersIndexRoute: typeof MetiersIndexRoute
}

const MetiersRouteChildren: MetiersRouteChildren = {
  MetiersSlugRoute: MetiersSlugRoute,
  MetiersIndexRoute: MetiersIndexRoute,
}

const MetiersRouteWithChildren =
  MetiersRoute._addFileChildren(MetiersRouteChildren)

interface SavoirsCatRouteChildren {
  SavoirsCatSlugRoute: typeof SavoirsCatSlugRoute
  SavoirsCatIndexRoute: typeof SavoirsCatIndexRoute
}

const SavoirsCatRouteChildren: SavoirsCatRouteChildren = {
  SavoirsCatSlugRoute: SavoirsCatSlugRoute,
  SavoirsCatIndexRoute: SavoirsCatIndexRoute,
}

const SavoirsCatRouteWithChildren = SavoirsCatRoute._addFileChildren(
  SavoirsCatRouteChildren,
)

interface SavoirsRouteChildren {
  SavoirsCatRoute: typeof SavoirsCatRouteWithChildren
  SavoirsIndexRoute: typeof SavoirsIndexRoute
}

const SavoirsRouteChildren: SavoirsRouteChildren = {
  SavoirsCatRoute: SavoirsCatRouteWithChildren,
  SavoirsIndexRoute: SavoirsIndexRoute,
}

const SavoirsRouteWithChildren =
  SavoirsRoute._addFileChildren(SavoirsRouteChildren)

interface ViviersRouteChildren {
  ViviersSlugRoute: typeof ViviersSlugRoute
  ViviersIndexRoute: typeof ViviersIndexRoute
}

const ViviersRouteChildren: ViviersRouteChildren = {
  ViviersSlugRoute: ViviersSlugRoute,
  ViviersIndexRoute: ViviersIndexRoute,
}

const ViviersRouteWithChildren =
  ViviersRoute._addFileChildren(ViviersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiesRoute: AcademiesRoute,
  AdminRoute: AdminRoute,
  ApprendreRoute: ApprendreRouteWithChildren,
  CoachRoute: CoachRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DriveRoute: DriveRouteWithChildren,
  EuropeRoute: EuropeRoute,
  FeedDotjsonRoute: FeedDotjsonRoute,
  GuidesRoute: GuidesRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  LexiqueRoute: LexiqueRoute,
  LieuxRoute: LieuxRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  MarcheRoute: MarcheRoute,
  MarchesRoute: MarchesRoute,
  MeRoute: MeRouteWithChildren,
  MetiersRoute: MetiersRouteWithChildren,
  PacteRoute: PacteRoute,
  PassportRoute: PassportRoute,
  PostRoute: PostRoute,
  PpqcRoute: PpqcRoute,
  PreuveRoute: PreuveRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SavoirsRoute: SavoirsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TensionRoute: TensionRoute,
  ViviersRoute: ViviersRouteWithChildren,
  FeedSlugDotmdRoute: FeedSlugDotmdRoute,
  FichiersIdRoute: FichiersIdRoute,
  TalentsSlugRoute: TalentsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  FeedMaisonsSlugDotmdRoute: FeedMaisonsSlugDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
